#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
This code was written for /r/formula1
Written by /u/Redbiertje
11 Jan 2018
"""

#Imports
from __future__ import division
import datetime
import sys


prevYear = 2018
currYear = 2019

#Defines time for DD thread (UTC)
ddPostTime = 7

#Define list of Tech Talk Threads
techTalks = [datetime.datetime(currYear, 3, 14, 2, 00),
            datetime.datetime(currYear, 3, 21, 8, 00),
            datetime.datetime(currYear, 3, 28, 14, 00),
            datetime.datetime(currYear, 4, 4, 20, 00),
            datetime.datetime(currYear, 4, 11, 2, 00),
            datetime.datetime(currYear, 4, 18, 8, 00),
            datetime.datetime(currYear, 4, 25, 14, 00),
            datetime.datetime(currYear, 5, 2, 20, 00),
            datetime.datetime(currYear, 5, 9, 2, 00),
            datetime.datetime(currYear, 5, 16, 21, 45),
            datetime.datetime(currYear, 5, 22, 14, 00),
            datetime.datetime(currYear, 5, 30, 20, 00),
            datetime.datetime(currYear, 6, 6, 2, 00),
            datetime.datetime(currYear, 6, 13, 8, 00),
            datetime.datetime(currYear, 6, 20, 14, 00),
            datetime.datetime(currYear, 6, 27, 20, 00),
            datetime.datetime(currYear, 7, 4, 2, 00),
            datetime.datetime(currYear, 7, 11, 8, 00),
            datetime.datetime(currYear, 7, 18, 14, 00),
            datetime.datetime(currYear, 7, 25, 20, 00),
            datetime.datetime(currYear, 8, 1, 2, 00),
            datetime.datetime(currYear, 8, 8, 8, 00),
            datetime.datetime(currYear, 8, 15, 14, 00),
            datetime.datetime(currYear, 8, 22, 20, 00),
            datetime.datetime(currYear, 8, 29, 2, 00),
            datetime.datetime(currYear, 9, 5, 8, 00),
            datetime.datetime(currYear, 9, 12, 14, 00),
            datetime.datetime(currYear, 9, 19, 20, 00),
            datetime.datetime(currYear, 9, 26, 2, 00),
            datetime.datetime(currYear, 10, 3, 8, 00),
            datetime.datetime(currYear, 10, 10, 14, 00),
            datetime.datetime(currYear, 10, 17, 20, 00),
            datetime.datetime(currYear, 10, 24, 2, 00),
            datetime.datetime(currYear, 10, 31, 8, 00),
            datetime.datetime(currYear, 11, 7, 14, 00),
            datetime.datetime(currYear, 11, 14, 20, 00),
            datetime.datetime(currYear, 11, 21, 8, 00)]

#Define a nice object
class Weekend:
    """Contains all the parameters belonging to an F1 weekend"""
    
    def __init__(self, location):
        self.country = location

#Add properties to the Australia weekend
Australia = Weekend("Australia")
Australia.fullTitle = "FORMULA 1 ROLEX AUSTRALIAN GRAND PRIX 2020"
Australia.round = 1
Australia.racenr = 1021
Australia.hubTime = datetime.datetime(currYear+1, 3, 12, 9, 00)
Australia.fp1Time = datetime.datetime(currYear+1, 3, 13, 1, 00)
Australia.fp2Time = datetime.datetime(currYear+1, 3, 13, 5, 00)
Australia.fp3Time = datetime.datetime(currYear+1, 3, 14, 3, 00)
Australia.qualiTime = datetime.datetime(currYear+1, 3, 14, 6, 00)
Australia.raceTime = datetime.datetime(currYear+1, 3, 15, 5, 10)
Australia.dadTime = datetime.datetime(currYear+1, 3, 16, 5, 00)
Australia.namean = "Australian"
Australia.flag = "#au"
Australia.circuit = "Melbourne Grand Prix Circuit"
Australia.city = "Melbourne"
Australia.weatherID = 2158177
Australia.firstHeld = 1928
Australia.length = 5.303
Australia.laps = 58
Australia.distance = 307.574
Australia.poleLeft = True
Australia.lastYear = prevYear
Australia.lapRecordTime = "1:24.125"
Australia.lapRecordFlag = "#de"
Australia.lapRecordHolder = "Michael Schumacher"
Australia.lapRecordTeam = "Ferrari"
Australia.lapRecordYear = 2004
Australia.prevYearPoleFlag = "#gb"
Australia.prevYearPoleHolder = "Lewis Hamilton"
Australia.prevYearPoleTeam = "Mercedes"
Australia.prevYearPoleTime = "1:20.486"
Australia.prevYearFastestFlag = "#fi"
Australia.prevYearFastestHolder = "Valtteri Bottas"
Australia.prevYearFastestTeam = "Mercedes"
Australia.prevYearFastestTime = "1:25.580"
Australia.prevYearWinnerFlag = "#fi"
Australia.prevYearWinner = "Valtteri Bottas"
Australia.prevYearWinnerTeam = "Mercedes"
Australia.prevYearSecondFlag = "#gb"
Australia.prevYearSecond = "Lewis Hamilton"
Australia.prevYearSecondTeam = "Mercedes"
Australia.prevYearSecondDelta = "+20.886"
Australia.prevYearThirdFlag = "#nl"
Australia.prevYearThird = "M. Verstappen"
Australia.prevYearThirdTeam = "Red Bull Racing-Honda"
Australia.prevYearThirdDelta = "+22.520"
Australia.linkF1 = "https://www.formula1.com/en/racing/2020/Australia.html"
Australia.linkWikiCircuit = "https://en.wikipedia.org/wiki/Melbourne_Grand_Prix_Circuit"
Australia.linkWikiRace = "https://en.wikipedia.org/wiki/Australian_Grand_Prix"

#Add properties to the Bahrain weekend
Bahrain = Weekend("Bahrain")
Bahrain.fullTitle = "FORMULA 1 GULF AIR BAHRAIN GRAND PRIX 2020"
Bahrain.round = 2
Bahrain.racenr = 1022
Bahrain.hubTime = datetime.datetime(currYear, 3, 28, 20, 00)
Bahrain.fp1Time = datetime.datetime(currYear, 3, 29, 11, 00)
Bahrain.fp2Time = datetime.datetime(currYear, 3, 29, 15, 00)
Bahrain.fp3Time = datetime.datetime(currYear, 3, 30, 12, 00)
Bahrain.qualiTime = datetime.datetime(currYear, 3, 30, 15, 00)
Bahrain.raceTime = datetime.datetime(currYear, 3, 31, 15, 10)
Bahrain.dadTime = datetime.datetime(currYear, 4, 1, 15, 00)
Bahrain.namean = "Bahrain"
Bahrain.flag = "#bh"
Bahrain.circuit = "Bahrain International Circuit"
Bahrain.city = "Sakhir"
Bahrain.weatherID = 290104
Bahrain.firstHeld = 2004
Bahrain.length = 5.412
Bahrain.laps = 57
Bahrain.distance = 308.238
Bahrain.poleLeft = True
Bahrain.lastYear = prevYear
Bahrain.lapRecordTime = "1:31.447"
Bahrain.lapRecordFlag = "#es"
Bahrain.lapRecordHolder = "Pedro de la Rosa"
Bahrain.lapRecordTeam = "McLaren"
Bahrain.lapRecordYear = 2005
Bahrain.prevYearPoleFlag = "#mc"
Bahrain.prevYearPoleHolder = "Charles Leclerc"
Bahrain.prevYearPoleTeam = "Ferrari"
Bahrain.prevYearPoleTime = "1:27.866"
Bahrain.prevYearFastestFlag = "#mc"
Bahrain.prevYearFastestHolder = "Charles Leclerc"
Bahrain.prevYearFastestTeam = "Ferrari"
Bahrain.prevYearFastestTime = "1:33.411"
Bahrain.prevYearWinnerFlag = "#gb"
Bahrain.prevYearWinner = "Lewis Hamilton"
Bahrain.prevYearWinnerTeam = "Mercedes"
Bahrain.prevYearSecondFlag = "#fi"
Bahrain.prevYearSecond = "Valtteri Bottas"
Bahrain.prevYearSecondTeam = "Mercedes"
Bahrain.prevYearSecondDelta = "+2.980"
Bahrain.prevYearThirdFlag = "#mc"
Bahrain.prevYearThird = "Charles Leclerc"
Bahrain.prevYearThirdTeam = "Ferrari"
Bahrain.prevYearThirdDelta = "+6.131"
Bahrain.linkF1 = "https://www.formula1.com/en/racing/2020/Bahrain.html"
Bahrain.linkWikiCircuit = "https://en.wikipedia.org/wiki/Bahrain_International_Circuit"
Bahrain.linkWikiRace = "https://en.wikipedia.org/wiki/Bahrain_Grand_Prix"

#Add properties to the China weekend
China = Weekend("China")
China.fullTitle = "FORMULA 1 HEINEKEN CHINESE GRAND PRIX 2020"
China.round = 3
China.racenr = 1023
China.hubTime = datetime.datetime(currYear, 4, 11, 14, 00)
China.fp1Time = datetime.datetime(currYear, 4, 12, 2, 00)
China.fp2Time = datetime.datetime(currYear, 4, 12, 6, 00)
China.fp3Time = datetime.datetime(currYear, 4, 13, 3, 00)
China.qualiTime = datetime.datetime(currYear, 4, 13, 6, 00)
China.raceTime = datetime.datetime(currYear, 4, 14, 6, 10)
China.dadTime = datetime.datetime(currYear, 4, 15, 6, 00)
China.namean = "Chinese"
China.flag = "#cn"
China.circuit = "Shanghai International Circuit"
China.city = "Shanghai"
China.weatherID = 1796236
China.firstHeld = 2004
China.length = 5.451
China.laps = 56
China.distance = 305.066
China.poleLeft = True
China.lastYear = prevYear
China.lapRecordTime = "1:32.238"
China.lapRecordFlag = "#de"
China.lapRecordHolder = "Michael Schumacher"
China.lapRecordTeam = "Ferrari"
China.lapRecordYear = 2004
China.prevYearPoleFlag = "#fi"
China.prevYearPoleHolder = "Valtteri Bottas"
China.prevYearPoleTeam = "Mercedes"
China.prevYearPoleTime = "1:31.547"
China.prevYearFastestFlag = "#fr"
China.prevYearFastestHolder = "Pierre Gasly"
China.prevYearFastestTeam = "Red Bull Racing-Honda"
China.prevYearFastestTime = "1:34.742"
China.prevYearWinnerFlag = "#gb"
China.prevYearWinner = "Lewis Hamilton"
China.prevYearWinnerTeam = "Mercedes"
China.prevYearSecondFlag = "#fi"
China.prevYearSecond = "Valtteri Bottas"
China.prevYearSecondTeam = "Mercedes"
China.prevYearSecondDelta = "+6.552"
China.prevYearThirdFlag = "#de"
China.prevYearThird = "Sebastian Vettel"
China.prevYearThirdTeam = "Ferrari"
China.prevYearThirdDelta = "+13.744"
China.linkF1 = "https://www.formula1.com/en/racing/2020/China.html"
China.linkWikiCircuit = "https://en.wikipedia.org/wiki/Shanghai_International_Circuit"
China.linkWikiRace = "https://en.wikipedia.org/wiki/Chinese_Grand_Prix"

#Add properties to the Azerbaijan weekend
Azerbaijan = Weekend("Azerbaijan")
Azerbaijan.fullTitle = "FORMULA 1 AZERBAIJAN GRAND PRIX 2020"
Azerbaijan.round = 4
Azerbaijan.racenr = 1024
Azerbaijan.hubTime = datetime.datetime(currYear, 4, 25, 2, 00)
Azerbaijan.fp1Time = datetime.datetime(currYear, 4, 26, 9, 00)
Azerbaijan.fp2Time = datetime.datetime(currYear, 4, 26, 13, 00)
Azerbaijan.fp3Time = datetime.datetime(currYear, 4, 27, 10, 00)
Azerbaijan.qualiTime = datetime.datetime(currYear, 4, 27, 13, 00)
Azerbaijan.raceTime = datetime.datetime(currYear, 4, 28, 12, 10)
Azerbaijan.dadTime = datetime.datetime(currYear, 4, 29, 12, 10)
Azerbaijan.namean = "Azerbaijan"
Azerbaijan.flag = "#az"
Azerbaijan.circuit = "Baku City Circuit"
Azerbaijan.city = "Baku"
Azerbaijan.weatherID = 587084
Azerbaijan.firstHeld = 2016
Azerbaijan.length = 6.003
Azerbaijan.laps = 51
Azerbaijan.distance = 306.049
Azerbaijan.poleLeft = False
Azerbaijan.lastYear = prevYear
Azerbaijan.lapRecordTime = "1:43.009"
Azerbaijan.lapRecordFlag = "#mc"
Azerbaijan.lapRecordHolder = "Charles Leclerc"
Azerbaijan.lapRecordTeam = "Ferrari"
Azerbaijan.lapRecordYear = 2019
Azerbaijan.prevYearPoleFlag = "#fi"
Azerbaijan.prevYearPoleHolder = "Valtteri Bottas"
Azerbaijan.prevYearPoleTeam = "Mercedes"
Azerbaijan.prevYearPoleTime = "1:40.495"
Azerbaijan.prevYearFastestFlag = "#mc"
Azerbaijan.prevYearFastestHolder = "Charles Leclerc"
Azerbaijan.prevYearFastestTeam = "Ferrari"
Azerbaijan.prevYearFastestTime = "1:43.009"
Azerbaijan.prevYearWinnerFlag = "#fi"
Azerbaijan.prevYearWinner = "Valtteri Bottas"
Azerbaijan.prevYearWinnerTeam = "Mercedes"
Azerbaijan.prevYearSecondFlag = "#gb"
Azerbaijan.prevYearSecond = "Lewis Hamilton"
Azerbaijan.prevYearSecondTeam = "Mercedes"
Azerbaijan.prevYearSecondDelta = "+1.524"
Azerbaijan.prevYearThirdFlag = "#de"
Azerbaijan.prevYearThird = "Sebastian Vettel"
Azerbaijan.prevYearThirdTeam = "Ferrari"
Azerbaijan.prevYearThirdDelta = "+11.739"
Azerbaijan.linkF1 = "https://www.formula1.com/en/racing/2020/Azerbaijan.html"
Azerbaijan.linkWikiCircuit = "https://en.wikipedia.org/wiki/Baku_City_Circuit"
Azerbaijan.linkWikiRace = "https://en.wikipedia.org/wiki/Azerbaijan_Grand_Prix"

#Add properties to the Spain weekend
Spain = Weekend("Spain")
Spain.fullTitle = "FORMULA 1 EMIRATES GRAN PREMIO DE ESPAÑA 2020"
Spain.round = 5
Spain.racenr = 1004
Spain.hubTime = datetime.datetime(currYear, 5, 9, 8, 00)
Spain.fp1Time = datetime.datetime(currYear, 5, 10, 9, 00)
Spain.fp2Time = datetime.datetime(currYear, 5, 10, 13, 00)
Spain.fp3Time = datetime.datetime(currYear, 5, 11, 10, 00)
Spain.qualiTime = datetime.datetime(currYear, 5, 11, 13, 00)
Spain.raceTime = datetime.datetime(currYear, 5, 12, 13, 10)
Spain.dadTime = datetime.datetime(currYear, 5, 13, 13, 00)
Spain.namean = "Spanish"
Spain.flag = "#es"
Spain.circuit = "Circuit de Barcelona-Catalunya"
Spain.city = "Barcelona"
Spain.weatherID = 3128760
Spain.firstHeld = 1913
Spain.length = 4.655
Spain.laps = 66
Spain.distance = 307.104
Spain.poleLeft = True
Spain.lastYear = prevYear
Spain.lapRecordTime = "1:18.441"
Spain.lapRecordFlag = "#au"
Spain.lapRecordHolder = "Daniel Ricciardo"
Spain.lapRecordTeam = "Red Bull Racing-TAG Heuer"
Spain.lapRecordYear = 2018
Spain.prevYearPoleFlag = "#fi"
Spain.prevYearPoleHolder = "Valtteri Bottas"
Spain.prevYearPoleTeam = "Mercedes"
Spain.prevYearPoleTime = "1:15.406"
Spain.prevYearFastestFlag = "#gb"
Spain.prevYearFastestHolder = "Lewis Hamilton"
Spain.prevYearFastestTeam = "Mercedes"
Spain.prevYearFastestTime = "1:18.492"
Spain.prevYearWinnerFlag = "#gb"
Spain.prevYearWinner = "Lewis Hamilton"
Spain.prevYearWinnerTeam = "Mercedes"
Spain.prevYearSecondFlag = "#fi"
Spain.prevYearSecond = "Valtteri Bottas"
Spain.prevYearSecondTeam = "Mercedes"
Spain.prevYearSecondDelta = "+4.074"
Spain.prevYearThirdFlag = "#nl"
Spain.prevYearThird = "Max Verstappen"
Spain.prevYearThirdTeam = "Red Bull Racing-Honda"
Spain.prevYearThirdDelta = "+7.679"
Spain.linkF1 = "https://www.formula1.com/en/racing/2020/Spain.html"
Spain.linkWikiCircuit = "https://en.wikipedia.org/wiki/Circuit_de_Barcelona-Catalunya"
Spain.linkWikiRace = "https://en.wikipedia.org/wiki/Spanish_Grand_Prix"

#Add properties to the Monaco weekend
Monaco = Weekend("Monaco")
Monaco.fullTitle = "FORMULA 1 GRAND PRIX DE MONACO 2020"
Monaco.round = 6
Monaco.racenr = 1005
Monaco.hubTime = datetime.datetime(currYear, 5, 22, 14, 00)
Monaco.fp1Time = datetime.datetime(currYear, 5, 23, 9, 00)
Monaco.fp2Time = datetime.datetime(currYear, 5, 23, 13, 00)
Monaco.fp3Time = datetime.datetime(currYear, 5, 25, 10, 00)
Monaco.qualiTime = datetime.datetime(currYear, 5, 25, 13, 00)
Monaco.raceTime = datetime.datetime(currYear, 5, 26, 13, 10)
Monaco.dadTime = datetime.datetime(currYear, 5, 27, 13, 00)
Monaco.namean = "Monaco"
Monaco.flag = "#mc"
Monaco.circuit = "Circuit de Monaco"
Monaco.city = "Monte Carlo"
Monaco.weatherID = 2993458
Monaco.firstHeld = 1929
Monaco.length = 3.337
Monaco.laps = 78
Monaco.distance = 260.286
Monaco.poleLeft = False
Monaco.lastYear = prevYear
Monaco.lapRecordTime = "1:14.260"
Monaco.lapRecordFlag = "#nl"
Monaco.lapRecordHolder = "Max Verstappen"
Monaco.lapRecordTeam = "Red Bull Racing-TAG Heuer"
Monaco.lapRecordYear = 2018
Monaco.prevYearPoleFlag = "#gb"
Monaco.prevYearPoleHolder = "Lewis Hamilton"
Monaco.prevYearPoleTeam = "Mercedes"
Monaco.prevYearPoleTime = "1:10.166"
Monaco.prevYearFastestFlag = "#fr"
Monaco.prevYearFastestHolder = "Pierre Gasly"
Monaco.prevYearFastestTeam = "Red Bull Racing-Honda"
Monaco.prevYearFastestTime = "1:14.279"
Monaco.prevYearWinnerFlag = "#gb"
Monaco.prevYearWinner = "Lewis Hamilton"
Monaco.prevYearWinnerTeam = "Mercedes"
Monaco.prevYearSecondFlag = "#de"
Monaco.prevYearSecond = "Sebastian Vettel"
Monaco.prevYearSecondTeam = "Ferrari"
Monaco.prevYearSecondDelta = "+2.606"
Monaco.prevYearThirdFlag = "#fi"
Monaco.prevYearThird = "Valtteri Bottas"
Monaco.prevYearThirdTeam = "Mercedes"
Monaco.prevYearThirdDelta = "+3.162"
Monaco.linkF1 = "https://www.formula1.com/en/racing/2020/Monaco.html"
Monaco.linkWikiCircuit = "https://en.wikipedia.org/wiki/Circuit_de_Monaco"
Monaco.linkWikiRace = "https://en.wikipedia.org/wiki/Monaco_Grand_Prix"

#Add properties to the Canada weekend
Canada = Weekend("Canada")
Canada.fullTitle = "FORMULA 1 PIRELLI GRAND PRIX DU CANADA 2020"
Canada.round = 7
Canada.racenr = 1006
Canada.hubTime = datetime.datetime(currYear, 6, 6, 20, 00)
Canada.fp1Time = datetime.datetime(currYear, 6, 7, 14, 00)
Canada.fp2Time = datetime.datetime(currYear, 6, 7, 18, 00)
Canada.fp3Time = datetime.datetime(currYear, 6, 8, 15, 00)
Canada.qualiTime = datetime.datetime(currYear, 6, 8, 18, 00)
Canada.raceTime = datetime.datetime(currYear, 6, 9, 18, 10)
Canada.dadTime = datetime.datetime(currYear, 6, 10, 12, 45)
Canada.namean = "Canadian"
Canada.flag = "#ca"
Canada.circuit = "Circuit Gilles Villeneuve"
Canada.city = "Montreal"
Canada.weatherID = 6077243
Canada.firstHeld = 1961
Canada.length = 4.361
Canada.laps = 70
Canada.distance = 305.270
Canada.poleLeft = True
Canada.lastYear = prevYear
Canada.lapRecordTime = "1:13.078"
Canada.lapRecordFlag = "#fi"
Canada.lapRecordHolder = "Valtteri Bottas"
Canada.lapRecordTeam = "Mercedes"
Canada.lapRecordYear = 2019
Canada.prevYearPoleFlag = "#de"
Canada.prevYearPoleHolder = "Sebastian Vettel"
Canada.prevYearPoleTeam = "Ferrari"
Canada.prevYearPoleTime = "1:10.240"
Canada.prevYearFastestFlag = "#fi"
Canada.prevYearFastestHolder = "Valtteri Bottas"
Canada.prevYearFastestTeam = "Mercedes"
Canada.prevYearFastestTime = "1:13.078"
Canada.prevYearWinnerFlag = "#gb"
Canada.prevYearWinner = "Lewis Hamilton"
Canada.prevYearWinnerTeam = "Mercedes"
Canada.prevYearSecondFlag = "#de"
Canada.prevYearSecond = "Sebastian Vettel"
Canada.prevYearSecondTeam = "Ferrari"
Canada.prevYearSecondDelta = "+3.658"
Canada.prevYearThirdFlag = "#mc"
Canada.prevYearThird = "Charles Leclerc"
Canada.prevYearThirdTeam = "Ferrari"
Canada.prevYearThirdDelta = "+4.696"
Canada.linkF1 = "https://www.formula1.com/en/racing/2020/Canada.html"
Canada.linkWikiCircuit = "https://en.wikipedia.org/wiki/Circuit_Gilles_Villeneuve"
Canada.linkWikiRace = "https://en.wikipedia.org/wiki/Canadian_Grand_Prix"

#Add properties to the France weekend
France = Weekend("France")
France.fullTitle = "FORMULA 1 GRAND PRIX DE FRANCE 2020"
France.round = 8
France.racenr = 1007
France.hubTime = datetime.datetime(currYear, 6, 20, 20, 00)
France.fp1Time = datetime.datetime(currYear, 6, 21, 9, 00)
France.fp2Time = datetime.datetime(currYear, 6, 21, 13, 00)
France.fp3Time = datetime.datetime(currYear, 6, 22, 10, 00)
France.qualiTime = datetime.datetime(currYear, 6, 22, 13, 00)
France.raceTime = datetime.datetime(currYear, 6, 23, 13, 10)
France.dadTime = datetime.datetime(currYear, 6, 24, 13, 00)
France.namean = "French"
France.flag = "#fr"
France.circuit = "Circuit Paul Ricard"
France.city = "Le Castellet"
France.weatherID = 3004838
France.firstHeld = 1906
France.length = 5.842
France.laps = 53
France.distance = 309.626
France.poleLeft = True
France.lastYear = prevYear
France.lapRecordTime = "1:32.720"
France.lapRecordFlag = "#de"
France.lapRecordHolder = "Sebastian Vettel"
France.lapRecordTeam = "Ferrari"
France.lapRecordYear = "2019"
France.prevYearPoleFlag = "#gb"
France.prevYearPoleHolder = "Lewis Hamilton"
France.prevYearPoleTeam = "Mercedes"
France.prevYearPoleTime = "1:28.319"
France.prevYearFastestFlag = "#de"
France.prevYearFastestHolder = "Sebastian Vettel"
France.prevYearFastestTeam = "Ferrari"
France.prevYearFastestTime = "1:32.720"
France.prevYearWinnerFlag = "#gb"
France.prevYearWinner = "Lewis Hamilton"
France.prevYearWinnerTeam = "Mercedes"
France.prevYearSecondFlag = "#fi"
France.prevYearSecond = "Valtteri Bottas"
France.prevYearSecondTeam = "Mercedes"
France.prevYearSecondDelta = "+18.056"
France.prevYearThirdFlag = "#mc"
France.prevYearThird = "Charles Leclerc"
France.prevYearThirdTeam = "Ferrari"
France.prevYearThirdDelta = "+18.985"
France.linkF1 = "https://www.formula1.com/en/racing/2020/France.html"
France.linkWikiCircuit = "https://en.wikipedia.org/wiki/Circuit_Paul_Ricard"
France.linkWikiRace = "https://en.wikipedia.org/wiki/French_Grand_Prix"

#Add properties to the Austria weekend
Austria = Weekend("Austria")
Austria.fullTitle = "FORMULA 1 MYWORLD GROSSER PREIS VON ÖSTERREICH 2020"
Austria.round = 9
Austria.racenr = 1008
Austria.hubTime = datetime.datetime(currYear, 6, 27, 8, 00)
Austria.fp1Time = datetime.datetime(currYear, 6, 28, 9, 00)
Austria.fp2Time = datetime.datetime(currYear, 6, 28, 13, 00)
Austria.fp3Time = datetime.datetime(currYear, 6, 29, 10, 00)
Austria.qualiTime = datetime.datetime(currYear, 6, 29, 13, 00)
Austria.raceTime = datetime.datetime(currYear, 6, 30, 13, 10)
Austria.dadTime = datetime.datetime(currYear, 7, 1, 13, 00)
Austria.namean = "Austrian"
Austria.flag = "#at"
Austria.circuit = "Red Bull Ring"
Austria.city = "Spielberg"
Austria.weatherID = 2773887
Austria.firstHeld = 1963
Austria.length = 4.318
Austria.laps = 71
Austria.distance = 307.146
Austria.poleLeft = True
Austria.lastYear = prevYear
Austria.lapRecordTime = "1:06.957"
Austria.lapRecordFlag = "#fi"
Austria.lapRecordHolder = "Kimi Räikkönen"
Austria.lapRecordTeam = "Ferrari"
Austria.lapRecordYear = 2018
Austria.prevYearPoleFlag = "#mc"
Austria.prevYearPoleHolder = "Charles Leclerc"
Austria.prevYearPoleTeam = "Ferrari"
Austria.prevYearPoleTime = "1:03.003"
Austria.prevYearFastestFlag = "#nl"
Austria.prevYearFastestHolder = "Max Verstappen"
Austria.prevYearFastestTeam = "Red Bull Racing-Honda"
Austria.prevYearFastestTime = "1:07.475"
Austria.prevYearWinnerFlag = "#nl"
Austria.prevYearWinner = "Max Verstappen"
Austria.prevYearWinnerTeam = "Red Bull Racing-Honda"
Austria.prevYearSecondFlag = "#mc"
Austria.prevYearSecond = "Charles Leclerc"
Austria.prevYearSecondTeam = "Ferrari"
Austria.prevYearSecondDelta = "+2.724"
Austria.prevYearThirdFlag = "#fi"
Austria.prevYearThird = "Valtteri Bottas"
Austria.prevYearThirdTeam = "Mercedes"
Austria.prevYearThirdDelta = "+18.960"
Austria.linkF1 = "https://www.formula1.com/en/racing/2020/Austria.html"
Austria.linkWikiCircuit = "https://en.wikipedia.org/wiki/Red_Bull_Ring"
Austria.linkWikiRace = "https://en.wikipedia.org/wiki/Austrian_Grand_Prix"

#Add properties to the Britain weekend
Britain = Weekend("Great Britain")
Britain.fullTitle = "FORMULA 1 ROLEX BRITISH GRAND PRIX 2020"
Britain.round = 10
Britain.racenr = 1009
Britain.hubTime = datetime.datetime(currYear, 7, 11, 22, 00)
Britain.fp1Time = datetime.datetime(currYear, 7, 12, 9, 00)
Britain.fp2Time = datetime.datetime(currYear, 7, 12, 13, 00)
Britain.fp3Time = datetime.datetime(currYear, 7, 13, 10, 00)
Britain.qualiTime = datetime.datetime(currYear, 7, 13, 13, 00)
Britain.raceTime = datetime.datetime(currYear, 7, 14, 13, 10)
Britain.dadTime = datetime.datetime(currYear, 7, 15, 13, 00)
Britain.namean = "British"
Britain.flag = "#gb"
Britain.circuit = "Silverstone Circuit"
Britain.city = "Silverstone"
Britain.weatherID = 2642465
Britain.firstHeld = 1926
Britain.length = 5.891
Britain.laps = 52
Britain.distance = 306.291
Britain.poleLeft = True
Britain.lastYear = prevYear
Britain.lapRecordTime = "1:27.369"
Britain.lapRecordFlag = "#gb"
Britain.lapRecordHolder = "Lewis Hamilton"
Britain.lapRecordTeam = "Mercedes"
Britain.lapRecordYear = 2019
Britain.prevYearPoleFlag = "#fi"
Britain.prevYearPoleHolder = "Valtteri Bottas"
Britain.prevYearPoleTeam = "Mercedes"
Britain.prevYearPoleTime = "1:25.093"
Britain.prevYearFastestFlag = "#gb"
Britain.prevYearFastestHolder = "Lewis Hamilton"
Britain.prevYearFastestTeam = "Mercedes"
Britain.prevYearFastestTime = "1:27.369"
Britain.prevYearWinnerFlag = "#gb"
Britain.prevYearWinner = "Lewis Hamilton"
Britain.prevYearWinnerTeam = "Mercedes"
Britain.prevYearSecondFlag = "#fi"
Britain.prevYearSecond = "Valtteri Bottas"
Britain.prevYearSecondTeam = "Mercedes"
Britain.prevYearSecondDelta = "+24.928"
Britain.prevYearThirdFlag = "#mc"
Britain.prevYearThird = "Charles Leclerc"
Britain.prevYearThirdTeam = "Ferrari"
Britain.prevYearThirdDelta = "+30.117"
Britain.linkF1 = "https://www.formula1.com/en/racing/2020/Great_Britain.html"
Britain.linkWikiCircuit = "https://en.wikipedia.org/wiki/Silverstone_Circuit"
Britain.linkWikiRace = "https://en.wikipedia.org/wiki/British_Grand_Prix"

#Add properties to the Hungary weekend
Hungary = Weekend("Hungary")
Hungary.fullTitle = "FORMULA 1 PIRELLI MAGYAR NAGYDÍJ 2020"
Hungary.round = 12
Hungary.racenr = 1011
Hungary.hubTime = datetime.datetime(currYear, 8, 1, 20, 00)
Hungary.fp1Time = datetime.datetime(currYear, 8, 2, 9, 00)
Hungary.fp2Time = datetime.datetime(currYear, 8, 2, 13, 00)
Hungary.fp3Time = datetime.datetime(currYear, 8, 3, 10, 00)
Hungary.qualiTime = datetime.datetime(currYear, 8, 3, 13, 00)
Hungary.raceTime = datetime.datetime(currYear, 8, 4, 13, 10)
Hungary.dadTime = datetime.datetime(currYear, 8, 5, 13, 00)
Hungary.namean = "Hungarian"
Hungary.flag = "#hu"
Hungary.circuit = "Hungaroring"
Hungary.city = "Budapest"
Hungary.weatherID = 3054643
Hungary.firstHeld = 1936
Hungary.length = 4.381
Hungary.laps = 70
Hungary.distance = 306.663
Hungary.poleLeft = True
Hungary.lastYear = prevYear
Hungary.lapRecordTime = "1:17.103"
Hungary.lapRecordFlag = "#nl"
Hungary.lapRecordHolder = "Max Verstappen"
Hungary.lapRecordTeam = "Red Bull Racing-Honda"
Hungary.lapRecordYear = 2019
Hungary.prevYearPoleFlag = "#nl"
Hungary.prevYearPoleHolder = "Max Verstappen"
Hungary.prevYearPoleTeam = "Red Bull Racing-Honda"
Hungary.prevYearPoleTime = "1:14.572"
Hungary.prevYearFastestFlag = "#nl"
Hungary.prevYearFastestHolder = "Max Verstappen"
Hungary.prevYearFastestTeam = "Red Bull Racing-Honda"
Hungary.prevYearFastestTime = "1:17.103"
Hungary.prevYearWinnerFlag = "#gb"
Hungary.prevYearWinner = "Lewis Hamilton"
Hungary.prevYearWinnerTeam = "Mercedes"
Hungary.prevYearSecondFlag = "#nl"
Hungary.prevYearSecond = "Max Verstappen"
Hungary.prevYearSecondTeam = "Red Bull Racing-Honda"
Hungary.prevYearSecondDelta = "+17.796"
Hungary.prevYearThirdFlag = "#de"
Hungary.prevYearThird = "Sebastian Vettel"
Hungary.prevYearThirdTeam = "Ferrari"
Hungary.prevYearThirdDelta = "+1:01.433"
Hungary.linkF1 = "https://www.formula1.com/en/racing/2020/Hungary.html"
Hungary.linkWikiCircuit = "https://en.wikipedia.org/wiki/Hungaroring"
Hungary.linkWikiRace = "https://en.wikipedia.org/wiki/Hungarian_Grand_Prix"

#Add properties to the Belgium weekend
Belgium = Weekend("Belgium")
Belgium.fullTitle = "FORMULA 1 JOHNNIE WALKER BELGIAN GRAND PRIX 2020"
Belgium.round = 13
Belgium.racenr = 1012
Belgium.hubTime = datetime.datetime(currYear, 8, 29, 2, 00)
Belgium.fp1Time = datetime.datetime(currYear, 8, 30, 9, 00)
Belgium.fp2Time = datetime.datetime(currYear, 8, 30, 13, 00)
Belgium.fp3Time = datetime.datetime(currYear, 8, 31, 10, 00)
Belgium.qualiTime = datetime.datetime(currYear, 8, 31, 13, 00)
Belgium.raceTime = datetime.datetime(currYear, 9, 1, 13, 10)
Belgium.dadTime = datetime.datetime(currYear, 9, 2, 13, 00)
Belgium.namean = "Belgian"
Belgium.flag = "#be"
Belgium.circuit = "Circuit de Spa-Francorchamps"
Belgium.city = "Spa-Francorchamps"
Belgium.weatherID = 2791834
Belgium.firstHeld = 1925
Belgium.length = 7.004
Belgium.laps = 44
Belgium.distance = 308.052
Belgium.poleLeft = False
Belgium.lastYear = prevYear
Belgium.lapRecordTime = "1:46.286"
Belgium.lapRecordFlag = "#fi"
Belgium.lapRecordHolder = "Valtteri Bottass"
Belgium.lapRecordTeam = "Mercedes"
Belgium.lapRecordYear = 2018
Belgium.prevYearPoleFlag = "#mc"
Belgium.prevYearPoleHolder = "Charles Leclerc"
Belgium.prevYearPoleTeam = "Ferrari"
Belgium.prevYearPoleTime = "1:42.519"
Belgium.prevYearFastestFlag = "#de"
Belgium.prevYearFastestHolder = "Sebastian Vettel"
Belgium.prevYearFastestTeam = "Ferrari"
Belgium.prevYearFastestTime = "1:46.406"
Belgium.prevYearWinnerFlag = "#mc"
Belgium.prevYearWinner = "Charles Leclerc"
Belgium.prevYearWinnerTeam = "Ferrari"
Belgium.prevYearSecondFlag = "#gb"
Belgium.prevYearSecond = "Lewis Hamilton"
Belgium.prevYearSecondTeam = "Mercedes"
Belgium.prevYearSecondDelta = "+0.981"
Belgium.prevYearThirdFlag = "#fi"
Belgium.prevYearThird = "Valtteri Bottas"
Belgium.prevYearThirdTeam = "Mercedes"
Belgium.prevYearThirdDelta = "+12.585"
Belgium.linkF1 = "https://www.formula1.com/en/racing/2020/Belgium.html"
Belgium.linkWikiCircuit = "https://en.wikipedia.org/wiki/Circuit_de_Spa-Francorchamps"
Belgium.linkWikiRace = "https://en.wikipedia.org/wiki/Belgian_Grand_Prix"

#Add properties to the Italy weekend
Italy = Weekend("Italy")
Italy.fullTitle = "FORMULA 1 GRAN PREMIO HEINEKEN D'ITALIA 2020"
Italy.round = 14
Italy.racenr = 1013
Italy.hubTime = datetime.datetime(currYear, 9, 5, 8, 00)
Italy.fp1Time = datetime.datetime(currYear, 9, 6, 9, 00)
Italy.fp2Time = datetime.datetime(currYear, 9, 6, 13, 00)
Italy.fp3Time = datetime.datetime(currYear, 9, 7, 10, 00)
Italy.qualiTime = datetime.datetime(currYear, 9, 7, 13, 00)
Italy.raceTime = datetime.datetime(currYear, 9, 8, 13, 10)
Italy.dadTime = datetime.datetime(currYear, 9, 9, 13, 00)
Italy.namean = "Italian"
Italy.flag = "#it"
Italy.circuit = "Autodromo Nazionale Monza"
Italy.city = "Monza"
Italy.weatherID = 3172629
Italy.firstHeld = 1921
Italy.length = 5.793
Italy.laps = 53
Italy.distance = 306.720
Italy.poleLeft = True
Italy.lastYear = prevYear
Italy.lapRecordTime = "1:21.046"
Italy.lapRecordFlag = "#br"
Italy.lapRecordHolder = "Rubens Barrichello"
Italy.lapRecordTeam = "Ferrari"
Italy.lapRecordYear = 2004
Italy.prevYearPoleFlag = "#gb"
Italy.prevYearPoleHolder = "Lewis Hamilton"
Italy.prevYearPoleTeam = "Mercedes"
Italy.prevYearPoleTime = "1:19.307"
Italy.prevYearFastestFlag = "#gb"
Italy.prevYearFastestHolder = "Lewis Hamilton"
Italy.prevYearFastestTeam = "Mercedes"
Italy.prevYearFastestTime = "1:21.779"
Italy.prevYearWinnerFlag = "#mc"
Italy.prevYearWinner = "Charles Leclerc"
Italy.prevYearWinnerTeam = "Ferrari"
Italy.prevYearSecondFlag = "#fi"
Italy.prevYearSecond = "Valterri Bottas"
Italy.prevYearSecondTeam = "Mercedes"
Italy.prevYearSecondDelta = "+0.835"
Italy.prevYearThirdFlag = "#gb"
Italy.prevYearThird = "Lewis Hamilton"
Italy.prevYearThirdTeam = "Mercedes"
Italy.prevYearThirdDelta = "+35.199"
Italy.linkF1 = "https://www.formula1.com/en/racing/2020/Italy.html"
Italy.linkWikiCircuit = "https://en.wikipedia.org/wiki/Autodromo_Nazionale_Monza"
Italy.linkWikiRace = "https://en.wikipedia.org/wiki/Italian_Grand_Prix"

#Add properties to the Singapore weekend
Singapore = Weekend("Singapore")
Singapore.fullTitle = "FORMULA 1 SINGAPORE AIRLINES SINGAPORE GRAND PRIX 2020"
Singapore.round = 15
Singapore.racenr = 1014
Singapore.hubTime = datetime.datetime(currYear, 9, 19, 14, 00)
Singapore.fp1Time = datetime.datetime(currYear, 9, 20, 8, 30)
Singapore.fp2Time = datetime.datetime(currYear, 9, 20, 12, 30)
Singapore.fp3Time = datetime.datetime(currYear, 9, 21, 10, 00)
Singapore.qualiTime = datetime.datetime(currYear, 9, 21, 13, 00)
Singapore.raceTime = datetime.datetime(currYear, 9, 22, 12, 10)
Singapore.dadTime = datetime.datetime(currYear, 9, 23, 12, 00)
Singapore.namean = "Singapore"
Singapore.flag = "#sg"
Singapore.circuit = "Marina Bay Street Circuit"
Singapore.city = "Singapore"
Singapore.weatherID = 1880252
Singapore.firstHeld = 1966
Singapore.length = 5.065
Singapore.laps = 61
Singapore.distance = 308.828
Singapore.poleLeft = False
Singapore.lastYear = prevYear
Singapore.lapRecordTime = "1:41.905"
Singapore.lapRecordFlag = "#dk"
Singapore.lapRecordHolder = "Kevin Magnussen"
Singapore.lapRecordTeam = "Haas-Ferrari"
Singapore.lapRecordYear = 2018
Singapore.prevYearPoleFlag = "#mc"
Singapore.prevYearPoleHolder = "Charles Leclerc"
Singapore.prevYearPoleTeam = "Ferrari"
Singapore.prevYearPoleTime = "1:36.217"
Singapore.prevYearFastestFlag = "#dk"
Singapore.prevYearFastestHolder = "Kevin Magnussen"
Singapore.prevYearFastestTeam = "Haas-Ferrari"
Singapore.prevYearFastestTime = "1:42.301"
Singapore.prevYearWinnerFlag = "#de"
Singapore.prevYearWinner = "Sebastian Vettel"
Singapore.prevYearWinnerTeam = "Ferrari"
Singapore.prevYearSecondFlag = "#mc"
Singapore.prevYearSecond = "Charles Leclerc"
Singapore.prevYearSecondTeam = "Ferrari"
Singapore.prevYearSecondDelta = "+2.641"
Singapore.prevYearThirdFlag = "#nl"
Singapore.prevYearThird = "Max Verstappen"
Singapore.prevYearThirdTeam = "Red Bull Racing-Honda"
Singapore.prevYearThirdDelta = "+3.821"
Singapore.linkF1 = "https://www.formula1.com/en/racing/2020/Singapore.html"
Singapore.linkWikiCircuit = "https://en.wikipedia.org/wiki/Marina_Bay_Street_Circuit"
Singapore.linkWikiRace = "https://en.wikipedia.org/wiki/Singapore_Grand_Prix"

#Add properties to the Russia weekend
Russia = Weekend("Russia")
Russia.fullTitle = "FORMULA 1 VTB RUSSIAN GRAND PRIX 2020"
Russia.round = 16
Russia.racenr = 1015
Russia.hubTime = datetime.datetime(currYear, 9, 26, 20, 00)
Russia.fp1Time = datetime.datetime(currYear, 9, 27, 8, 00)
Russia.fp2Time = datetime.datetime(currYear, 9, 27, 12, 00)
Russia.fp3Time = datetime.datetime(currYear, 9, 28, 9, 00)
Russia.qualiTime = datetime.datetime(currYear, 9, 28, 12, 00)
Russia.raceTime = datetime.datetime(currYear, 9, 29, 11, 10)
Russia.dadTime = datetime.datetime(currYear, 9, 30, 11, 00)
Russia.namean = "Russian"
Russia.flag = "#ru"
Russia.circuit = "Sochi Autodrom"
Russia.city = "Sochi"
Russia.weatherID = 491422
Russia.firstHeld = 1913
Russia.length = 5.838
Russia.laps = 53
Russia.distance = 309.732
Russia.poleLeft = True
Russia.lastYear = prevYear
Russia.lapRecordTime = "1:35.761"
Russia.lapRecordFlag = "#gb"
Russia.lapRecordHolder = "Lewis Hamilton"
Russia.lapRecordTeam = "Mercedes"
Russia.lapRecordYear = 2019
Russia.prevYearPoleFlag = "#mc"
Russia.prevYearPoleHolder = "Charles Leclerc"
Russia.prevYearPoleTeam = "Ferrari"
Russia.prevYearPoleTime = "1:31.628"
Russia.prevYearFastestFlag = "#gb"
Russia.prevYearFastestHolder = "Lewis Hamilton"
Russia.prevYearFastestTeam = "Mercedes"
Russia.prevYearFastestTime = "1:35.761"
Russia.prevYearWinnerFlag = "#gb"
Russia.prevYearWinner = "Lewis Hamilton"
Russia.prevYearWinnerTeam = "Mercedes"
Russia.prevYearSecondFlag = "#fi"
Russia.prevYearSecond = "Valtteri Bottas"
Russia.prevYearSecondTeam = "Mercedes"
Russia.prevYearSecondDelta = "+3.829"
Russia.prevYearThirdFlag = "#mc"
Russia.prevYearThird = "Charles Leclerc"
Russia.prevYearThirdTeam = "Ferrari"
Russia.prevYearThirdDelta = "+5.212"
Russia.linkF1 = "https://www.formula1.com/en/racing/2020/Russia.html"
Russia.linkWikiCircuit = "https://en.wikipedia.org/wiki/Sochi_Autodrom"
Russia.linkWikiRace = "https://en.wikipedia.org/wiki/Russian_Grand_Prix"

#Add properties to the Japan weekend
Japan = Weekend("Japan")
Japan.fullTitle = "FORMULA 1 JAPANESE GRAND PRIX 2020"
Japan.round = 17
Japan.racenr = 1016
Japan.hubTime = datetime.datetime(currYear, 10, 10, 8, 00)
Japan.fp1Time = datetime.datetime(currYear, 10, 11, 1, 00)
Japan.fp2Time = datetime.datetime(currYear, 10, 11, 5, 00)
Japan.fp3Time = datetime.datetime(currYear, 10, 12, 3, 00)
Japan.qualiTime = datetime.datetime(currYear, 10, 13, 1, 00) #Edited due to hurricane
Japan.raceTime = datetime.datetime(currYear, 10, 13, 5, 10)
Japan.dadTime = datetime.datetime(currYear, 10, 14, 5, 00)
Japan.namean = "Japanese"
Japan.flag = "#jp"
Japan.circuit = "Suzuka International Racing Course"
Japan.city = "Suzuka"
Japan.weatherID = 1851348
Japan.firstHeld = 1963
Japan.length = 5.807
Japan.laps = 53
Japan.distance = 307.573
Japan.poleLeft = True
Japan.lastYear = prevYear
Japan.lapRecordTime = "1:30.983"
Japan.lapRecordFlag = "#gb"
Japan.lapRecordHolder = "Lewis Hamilton"
Japan.lapRecordTeam = "Mercedes"
Japan.lapRecordYear = 2019
Japan.prevYearPoleFlag = "#de"
Japan.prevYearPoleHolder = "Sebastian Vettel"
Japan.prevYearPoleTeam = "Ferrari"
Japan.prevYearPoleTime = "1:27.064"
Japan.prevYearFastestFlag = "#gb"
Japan.prevYearFastestHolder = "Lewis Hamilton"
Japan.prevYearFastestTeam = "Mercedes"
Japan.prevYearFastestTime = "1:30.983"
Japan.prevYearWinnerFlag = "#fi"
Japan.prevYearWinner = "Valtteri Bottas"
Japan.prevYearWinnerTeam = "Mercedes"
Japan.prevYearSecondFlag = "#de"
Japan.prevYearSecond = "Sebastian Vettel"
Japan.prevYearSecondTeam = "Ferrari"
Japan.prevYearSecondDelta = "+13.343"
Japan.prevYearThirdFlag = "#gb"
Japan.prevYearThird = "Lewis Hamilton"
Japan.prevYearThirdTeam = "Mercedes"
Japan.prevYearThirdDelta = "+13.858"
Japan.linkF1 = "https://www.formula1.com/en/racing/2020/Japan.html"
Japan.linkWikiCircuit = "https://en.wikipedia.org/wiki/Suzuka_Circuit"
Japan.linkWikiRace = "https://en.wikipedia.org/wiki/Japanese_Grand_Prix"

#Add properties to the Mexico weekend
Mexico = Weekend("Mexico")
Mexico.fullTitle = "FORMULA 1 GRAN PREMIO DE MÉXICO 2020"
Mexico.round = 18
Mexico.racenr = 1017
Mexico.hubTime = datetime.datetime(currYear, 10, 24, 20, 00)
Mexico.fp1Time = datetime.datetime(currYear, 10, 25, 15, 00)
Mexico.fp2Time = datetime.datetime(currYear, 10, 25, 19, 00)
Mexico.fp3Time = datetime.datetime(currYear, 10, 26, 15, 00)
Mexico.qualiTime = datetime.datetime(currYear, 10, 26, 18, 00)
Mexico.raceTime = datetime.datetime(currYear, 10, 27, 19, 10)
Mexico.dadTime = datetime.datetime(currYear, 10, 28, 19, 00)
Mexico.namean = "Mexican"
Mexico.flag = "#mx"
Mexico.circuit = "Autódromo Hermanos Rodríguez"
Mexico.city = "Mexico City"
Mexico.weatherID = 3530597
Mexico.firstHeld = 1962
Mexico.length = 4.304
Mexico.laps = 71
Mexico.distance = 305.541
Mexico.poleLeft = True
Mexico.lastYear = prevYear
Mexico.lapRecordTime = "1:18.741"
Mexico.lapRecordFlag = "#fi"
Mexico.lapRecordHolder = "Valtteri Bottas"
Mexico.lapRecordTeam = "Mercedes"
Mexico.lapRecordYear = 2018
Mexico.prevYearPoleFlag = "#mc"
Mexico.prevYearPoleHolder = "Charles Leclerc"
Mexico.prevYearPoleTeam = "Ferrari"
Mexico.prevYearPoleTime = "1:15.024"
Mexico.prevYearFastestFlag = "#mc"
Mexico.prevYearFastestHolder = "Charles Leclerc"
Mexico.prevYearFastestTeam = "Ferrari"
Mexico.prevYearFastestTime = "1:19.232"
Mexico.prevYearWinnerFlag = "#gb"
Mexico.prevYearWinner = "Lewis Hamilton"
Mexico.prevYearWinnerTeam = "Mercedes"
Mexico.prevYearSecondFlag = "#de"
Mexico.prevYearSecond = "Sebastian Vettel"
Mexico.prevYearSecondTeam = "Ferrari"
Mexico.prevYearSecondDelta = "+1.766"
Mexico.prevYearThirdFlag = "#fi"
Mexico.prevYearThird = "Valtteri Bottas"
Mexico.prevYearThirdTeam = "Mercedes"
Mexico.prevYearThirdDelta = "+3.553"
Mexico.linkF1 = "https://www.formula1.com/en/racing/2020/Mexico.html"
Mexico.linkWikiCircuit = "https://en.wikipedia.org/wiki/Aut%C3%B3dromo_Hermanos_Rodr%C3%ADguez"
Mexico.linkWikiRace = "https://en.wikipedia.org/wiki/Mexican_Grand_Prix"

#Add properties to the United States weekend
US = Weekend("United States")
US.fullTitle = "FORMULA 1 UNITED STATES GRAND PRIX 2020"
US.round = 19
US.racenr = 1018
US.hubTime = datetime.datetime(currYear, 10, 31, 14, 00)
US.fp1Time = datetime.datetime(currYear, 11, 1, 16, 00)
US.fp2Time = datetime.datetime(currYear, 11, 1, 20, 00)
US.fp3Time = datetime.datetime(currYear, 11, 2, 18, 00)
US.qualiTime = datetime.datetime(currYear, 11, 2, 21, 00)
US.raceTime = datetime.datetime(currYear, 11, 3, 19, 10)
US.dadTime = datetime.datetime(currYear, 11, 4, 19, 00)
US.namean = "United States"
US.flag = "#us"
US.circuit = "Circuit of the Americas"
US.city = "Austin"
US.weatherID = 4671654
US.firstHeld = 1908
US.length = 5.513
US.laps = 56
US.distance = 308.896
US.poleLeft = False
US.lastYear = prevYear
US.lapRecordTime = "1:36.169"
US.lapRecordFlag = "#mc"
US.lapRecordHolder = "Charles Leclerc"
US.lapRecordTeam = "Ferrari"
US.lapRecordYear = 2019
US.prevYearPoleFlag = "#fi"
US.prevYearPoleHolder = "Valtteri Bottas"
US.prevYearPoleTeam = "Mercedes"
US.prevYearPoleTime = "1:32.029"
US.prevYearFastestFlag = "#mc"
US.prevYearFastestHolder = "Charles Leclerc"
US.prevYearFastestTeam = "Ferrari"
US.prevYearFastestTime = "1:36.169"
US.prevYearWinnerFlag = "#fi"
US.prevYearWinner = "Valtteri Bottas"
US.prevYearWinnerTeam = "Mercedes"
US.prevYearSecondFlag = "#gb"
US.prevYearSecond = "Lewis Hamilton"
US.prevYearSecondTeam = "Mercedes"
US.prevYearSecondDelta = "+4.148"
US.prevYearThirdFlag = "#nl"
US.prevYearThird = "Max Verstappen"
US.prevYearThirdTeam = "Red Bull Racing-Honda"
US.prevYearThirdDelta = "+5.002"
US.linkF1 = "https://www.formula1.com/en/racing/2020/United_States.html"
US.linkWikiCircuit = "https://en.wikipedia.org/wiki/Circuit_of_the_Americas"
US.linkWikiRace = "https://en.wikipedia.org/wiki/United_States_Grand_Prix"

#Add properties to the Brazil weekend
Brazil = Weekend("Brazil")
Brazil.fullTitle = "FORMULA 1 GRANDE PRÊMIO DO BRASIL 2020"
Brazil.round = 20
Brazil.racenr = 1019
Brazil.hubTime = datetime.datetime(currYear, 11, 14, 2, 00)
Brazil.fp1Time = datetime.datetime(currYear, 11, 15, 14, 00)
Brazil.fp2Time = datetime.datetime(currYear, 11, 15, 18, 00)
Brazil.fp3Time = datetime.datetime(currYear, 11, 16, 15, 00)
Brazil.qualiTime = datetime.datetime(currYear, 11, 16, 18, 00)
Brazil.raceTime = datetime.datetime(currYear, 11, 17, 17, 10)
Brazil.dadTime = datetime.datetime(currYear, 11, 18, 17, 00)
Brazil.namean = "Brazilian"
Brazil.flag = "#br"
Brazil.circuit = "Autódromo José Carlos Pace"
Brazil.city = "São Paulo"
Brazil.weatherID = 3448439
Brazil.firstHeld = 1972
Brazil.length = 4.309
Brazil.laps = 71
Brazil.distance = 305.909
Brazil.poleLeft = False
Brazil.lastYear = prevYear
Brazil.lapRecordTime = "1:10.540"
Brazil.lapRecordFlag = "#fi"
Brazil.lapRecordHolder = "Valtteri Bottas"
Brazil.lapRecordTeam = "Mercedes"
Brazil.lapRecordYear = 2018
Brazil.prevYearPoleFlag = "#nl"
Brazil.prevYearPoleHolder = "Max Verstappen"
Brazil.prevYearPoleTeam = "Red Bull Racing-Honda"
Brazil.prevYearPoleTime = "1:07.508"
Brazil.prevYearFastestFlag = "#fi"
Brazil.prevYearFastestHolder = "Valtteri Bottas"
Brazil.prevYearFastestTeam = "Mercedes"
Brazil.prevYearFastestTime = "1:10.698"
Brazil.prevYearWinnerFlag = "#nl"
Brazil.prevYearWinner = "Max Verstappen"
Brazil.prevYearWinnerTeam = "Red Bull Racing-Honda"
Brazil.prevYearSecondFlag = "#fr"
Brazil.prevYearSecond = "Pierre Gasly"
Brazil.prevYearSecondTeam = "Scuderia Toro Rosso-Honda"
Brazil.prevYearSecondDelta = "+6.077"
Brazil.prevYearThirdFlag = "#es"
Brazil.prevYearThird = "Carlos Sainz Jr."
Brazil.prevYearThirdTeam = "McLaren-Renault"
Brazil.prevYearThirdDelta = "+8.896"
Brazil.linkF1 = "https://www.formula1.com/en/racing/2020/Brazil.html"
Brazil.linkWikiCircuit = "https://en.wikipedia.org/wiki/Aut%C3%B3dromo_Jos%C3%A9_Carlos_Pace"
Brazil.linkWikiRace = "https://en.wikipedia.org/wiki/Brazilian_Grand_Prix"

#Add properties to the Abu Dhabi weekend
AbuDhabi = Weekend("United Arab Emirates")
AbuDhabi.fullTitle = "FORMULA 1 ETIHAD AIRWAYS ABU DHABI GRAND PRIX 2019"
AbuDhabi.round = 21
AbuDhabi.racenr = 1020
AbuDhabi.hubTime = datetime.datetime(currYear, 11, 28, 8, 00)
AbuDhabi.fp1Time = datetime.datetime(currYear, 11, 29, 9, 00)
AbuDhabi.fp2Time = datetime.datetime(currYear, 11, 29, 13, 00)
AbuDhabi.fp3Time = datetime.datetime(currYear, 11, 30, 10, 00)
AbuDhabi.qualiTime = datetime.datetime(currYear, 11, 30, 13, 00)
AbuDhabi.raceTime = datetime.datetime(currYear, 12, 1, 13, 10)
AbuDhabi.dadTime = datetime.datetime(currYear, 12, 2, 13, 00)
AbuDhabi.namean = "Abu Dhabi"
AbuDhabi.flag = "#ae"
AbuDhabi.circuit = "Yas Marina Circuit"
AbuDhabi.city = "Abu Dhabi"
AbuDhabi.weatherID = 292968
AbuDhabi.firstHeld = 2009
AbuDhabi.length = 5.554
AbuDhabi.laps = 55
AbuDhabi.distance = 305.470
AbuDhabi.poleLeft = False
AbuDhabi.lastYear = prevYear
AbuDhabi.lapRecordTime = "1:40.279"
AbuDhabi.lapRecordFlag = "#de"
AbuDhabi.lapRecordHolder = "Sebastian Vettel"
AbuDhabi.lapRecordTeam = "Red Bull Racing"
AbuDhabi.lapRecordYear = 2009
AbuDhabi.prevYearPoleFlag = "#gb"
AbuDhabi.prevYearPoleHolder = "Lewis Hamilton"
AbuDhabi.prevYearPoleTeam = "Mercedes"
AbuDhabi.prevYearPoleTime = "1:34.794"
AbuDhabi.prevYearFastestFlag = "#de"
AbuDhabi.prevYearFastestHolder = "Sebastian Vettel"
AbuDhabi.prevYearFastestTeam = "Ferrari"
AbuDhabi.prevYearFastestTime = "1:40.867"
AbuDhabi.prevYearWinnerFlag = "#gb"
AbuDhabi.prevYearWinner = "Lewis Hamilton"
AbuDhabi.prevYearWinnerTeam = "Mercedes"
AbuDhabi.prevYearSecondFlag = "#de"
AbuDhabi.prevYearSecond = "Sebastian Vettel"
AbuDhabi.prevYearSecondTeam = "Ferrari"
AbuDhabi.prevYearSecondDelta = "+2.581"
AbuDhabi.prevYearThirdFlag = "#nl"
AbuDhabi.prevYearThird = "Max Verstappen"
AbuDhabi.prevYearThirdTeam = "Red Bull Racing-TAG Heuer"
AbuDhabi.prevYearThirdDelta = "+12.706"
AbuDhabi.linkF1 = "https://www.formula1.com/en/racing/2019/Abu_Dhabi.html"
AbuDhabi.linkWikiCircuit = "https://en.wikipedia.org/wiki/Yas_Marina_Circuit"
AbuDhabi.linkWikiRace = "https://en.wikipedia.org/wiki/Abu_Dhabi_Grand_Prix"

# RETIRED RACES

#Add properties to the Malaysia weekend
Malaysia = Weekend("Malaysia")
Malaysia.fullTitle = "2018 FORMULA 1 PETRONAS MALAYSIA GRAND PRIX"
Malaysia.round = 15
Malaysia.racenr = 973
Malaysia.hubTime = datetime.datetime(currYear, 9, 28, 2, 00)
Malaysia.fp1Time = datetime.datetime(currYear, 9, 29, 3, 00)
Malaysia.fp2Time = datetime.datetime(currYear, 9, 29, 7, 00)
Malaysia.fp3Time = datetime.datetime(currYear, 9, 30, 6, 00)
Malaysia.qualiTime = datetime.datetime(currYear, 9, 30, 9, 00)
Malaysia.raceTime = datetime.datetime(currYear, 10, 1, 7, 00)
Malaysia.dadTime = datetime.datetime(currYear, 10, 2, 7, 00)
Malaysia.namean = "Malaysian"
Malaysia.flag = "#my"
Malaysia.circuit = "Sepang International Circuit"
Malaysia.city = "Kuala Lumpur"
Malaysia.weatherID = 1771287
Malaysia.firstHeld = 1962
Malaysia.length = 5.543
Malaysia.laps = 56
Malaysia.distance = 310.408
Malaysia.poleLeft = False
Malaysia.lastYear = prevYear
Malaysia.lapRecordTime = "1:34.080"
Malaysia.lapRecordFlag = "#de"
Malaysia.lapRecordHolder = "Sebastian Vettel"
Malaysia.lapRecordTeam = "Ferrari"
Malaysia.lapRecordYear = 2017
Malaysia.prevYearPoleFlag = "#gb"
Malaysia.prevYearPoleHolder = "Lewis Hamilton"
Malaysia.prevYearPoleTeam = "Mercedes"
Malaysia.prevYearPoleTime = "1:30.076"
Malaysia.prevYearFastestFlag = "#de"
Malaysia.prevYearFastestHolder = "Sebastian Vettel"
Malaysia.prevYearFastestTeam = "Ferrari"
Malaysia.prevYearFastestTime = "1:34.080"
Malaysia.prevYearWinnerFlag = "#nl"
Malaysia.prevYearWinner = "Max Verstappen"
Malaysia.prevYearWinnerTeam = "Red Bull-TAG Heuer"
Malaysia.prevYearSecondFlag = "#gb"
Malaysia.prevYearSecond = "Lewis Hamilton"
Malaysia.prevYearSecondTeam = "Mercedes"
Malaysia.prevYearSecondDelta = "+12.770"
Malaysia.prevYearThirdFlag = "#au"
Malaysia.prevYearThird = "Daniel Ricciardo"
Malaysia.prevYearThirdTeam = "Red Bull-TAG Heuer"
Malaysia.prevYearThirdDelta = "+22.519"
Malaysia.linkF1 = "https://www.formula1.com/en/championship/races/2017/Malaysia"
Malaysia.linkWikiCircuit = "https://en.wikipedia.org/wiki/Sepang_International_Circuit"
Malaysia.linkWikiRace = "https://en.wikipedia.org/wiki/Malaysian_Grand_Prix"

#Add properties to the Germany weekend
Germany = Weekend("Germany")
Germany.fullTitle = "FORMULA 1 MERCEDES-BENZ GROSSER PREIS VON DEUTSCHLAND 2019"
Germany.round = 11
Germany.racenr = 1010
Germany.hubTime = datetime.datetime(currYear, 7, 25, 22, 00)
Germany.fp1Time = datetime.datetime(currYear, 7, 26, 9, 00)
Germany.fp2Time = datetime.datetime(currYear, 7, 26, 13, 00)
Germany.fp3Time = datetime.datetime(currYear, 7, 27, 10, 00)
Germany.qualiTime = datetime.datetime(currYear, 7, 27, 13, 00)
Germany.raceTime = datetime.datetime(currYear, 7, 28, 13, 10)
Germany.dadTime = datetime.datetime(currYear, 7, 29, 13, 00)
Germany.namean = "German"
Germany.flag = "#de"
Germany.circuit = "Hockenheimring"
Germany.city = "Hockenheim"
Germany.weatherID = 2902852
Germany.firstHeld = 1926
Germany.length = 4.574
Germany.laps = 67
Germany.distance = 306.442
Germany.poleLeft = True
Germany.lastYear = prevYear
Germany.lapRecordTime = "1:13.780"
Germany.lapRecordFlag = "#fi"
Germany.lapRecordHolder = "Kimi Räikkönen"
Germany.lapRecordTeam = "McLaren"
Germany.lapRecordYear = 2004
Germany.prevYearPoleFlag = "#de"
Germany.prevYearPoleHolder = "Sebastian Vettel"
Germany.prevYearPoleTeam = "Ferrari"
Germany.prevYearPoleTime = "1:11.212"
Germany.prevYearFastestFlag = "#gb"
Germany.prevYearFastestHolder = "Lewis Hamilton"
Germany.prevYearFastestTeam = "Mercedes"
Germany.prevYearFastestTime = "1:15.545"
Germany.prevYearWinnerFlag = "#gb"
Germany.prevYearWinner = "Lewis Hamilton"
Germany.prevYearWinnerTeam = "Mercedes"
Germany.prevYearSecondFlag = "#fi"
Germany.prevYearSecond = "Valtteri Bottas"
Germany.prevYearSecondTeam = "Mercedes"
Germany.prevYearSecondDelta = "+4.535"
Germany.prevYearThirdFlag = "#fi"
Germany.prevYearThird = "Kimi Räikkönen"
Germany.prevYearThirdTeam = "Ferrari"
Germany.prevYearThirdDelta = "+6.732"
Germany.linkF1 = "https://www.formula1.com/en/racing/2019/Germany.html"
Germany.linkWikiCircuit = "https://en.wikipedia.org/wiki/Hockenheimring"
Germany.linkWikiRace = "https://en.wikipedia.org/wiki/German_Grand_Prix"

#Add all weekends together (N.B.: Weekends must be added in CHRONOLOGICAL order)
allWeekends = [Bahrain, China, Azerbaijan, Spain, Monaco, Canada, France, Austria, Britain, Germany, Hungary, Belgium, Italy, Singapore, Russia, Japan, Mexico, US, Brazil, AbuDhabi, Australia]
