#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
This code was written for /r/formula1
Written by /u/Redbiertje
11 Jan 2018
"""

#Imports
from __future__ import division
import datetime
import sys

#Fix some weird problem
reload(sys)
sys.setdefaultencoding('utf-8')

prevYear = 2017
currYear = 2018

#Define list of Tech Talk Threads
techTalks = [datetime.datetime(currYear, 3, 23, 8, 00),
            datetime.datetime(currYear, 3, 30, 14, 00),
            datetime.datetime(currYear, 4, 5, 20, 00),
            datetime.datetime(currYear, 4, 12, 2, 00),
            datetime.datetime(currYear, 4, 19, 8, 00),
            datetime.datetime(currYear, 4, 26, 14, 00),
            datetime.datetime(currYear, 5, 3, 20, 00),
            datetime.datetime(currYear, 5, 10, 2, 00),
            datetime.datetime(currYear, 5, 17, 21, 45),
            datetime.datetime(currYear, 5, 23, 14, 00),
            datetime.datetime(currYear, 5, 31, 20, 00),
            datetime.datetime(currYear, 6, 7, 2, 00),
            datetime.datetime(currYear, 6, 14, 8, 00),
            datetime.datetime(currYear, 6, 21, 14, 00),
            datetime.datetime(currYear, 6, 28, 20, 00),
            datetime.datetime(currYear, 7, 5, 2, 00),
            datetime.datetime(currYear, 7, 12, 8, 00),
            datetime.datetime(currYear, 7, 19, 14, 00),
            datetime.datetime(currYear, 7, 26, 20, 00),
            datetime.datetime(currYear, 8, 2, 2, 00),
            datetime.datetime(currYear, 8, 9, 8, 00),
            datetime.datetime(currYear, 8, 16, 14, 00),
            datetime.datetime(currYear, 8, 23, 20, 00),
            datetime.datetime(currYear, 8, 30, 2, 00),
            datetime.datetime(currYear, 9, 6, 8, 00),
            datetime.datetime(currYear, 9, 13, 14, 00),
            datetime.datetime(currYear, 9, 20, 20, 00),
            datetime.datetime(currYear, 9, 27, 2, 00),
            datetime.datetime(currYear, 10, 4, 8, 00),
            datetime.datetime(currYear, 10, 11, 14, 00),
            datetime.datetime(currYear, 10, 18, 20, 00),
            datetime.datetime(currYear, 10, 25, 2, 00),
            datetime.datetime(currYear, 11, 1, 8, 00),
            datetime.datetime(currYear, 11, 8, 14, 00),
            datetime.datetime(currYear, 11, 15, 20, 00),
            datetime.datetime(currYear, 11, 22, 8, 00)]

#Define a nice object
class Weekend:
    """Contains all the parameters belonging to an F1 weekend"""
    
    def __init__(self, location):
        self.country = location

#Add properties to the Australia weekend
Australia = Weekend("Australia")
Australia.fullTitle = "2018 FORMULA 1 ROLEX AUSTRALIAN GRAND PRIX"
Australia.round = 1
Australia.racenr = 979
Australia.hubTime = datetime.datetime(currYear, 3, 22, 8, 00)
Australia.fp1Time = datetime.datetime(currYear, 3, 23, 1, 00)
Australia.fp2Time = datetime.datetime(currYear, 3, 23, 5, 00)
Australia.fp3Time = datetime.datetime(currYear, 3, 24, 3, 00)
Australia.qualiTime = datetime.datetime(currYear, 3, 24, 6, 00)
Australia.raceTime = datetime.datetime(currYear, 3, 25, 5, 10)
Australia.dadTime = datetime.datetime(currYear, 3, 26, 5, 00)
Australia.namean = "Australian"
Australia.flag = "#au"
Australia.circuit = "Melbourne Grand Prix Circuit"
Australia.city = "Melbourne"
Australia.weatherID = 2158177
Australia.firstHeld = 1928
Australia.length = 5.303
Australia.laps = 58
Australia.distance = 307.574
Australia.poleLeft = True
Australia.lastYear = prevYear
Australia.lapRecordTime = "1:24.125"
Australia.lapRecordFlag = "#de"
Australia.lapRecordHolder = "Michael Schumacher"
Australia.lapRecordTeam = "Ferrari"
Australia.lapRecordYear = 2004
Australia.prevYearPoleFlag = "#gb"
Australia.prevYearPoleHolder = "Lewis Hamilton"
Australia.prevYearPoleTeam = "Mercedes"
Australia.prevYearPoleTime = "1:22.188"
Australia.prevYearFastestFlag = "#fi"
Australia.prevYearFastestHolder = "Kimi Räikkönen"
Australia.prevYearFastestTeam = "Ferrari"
Australia.prevYearFastestTime = "1:26.538"
Australia.prevYearWinnerFlag = "#de"
Australia.prevYearWinner = "Sebastial Vettel"
Australia.prevYearWinnerTeam = "Ferrari"
Australia.prevYearSecondFlag = "#gb"
Australia.prevYearSecond = "Lewis Hamilton"
Australia.prevYearSecondTeam = "Mercedes"
Australia.prevYearSecondDelta = "+9.975"
Australia.prevYearThirdFlag = "#fi"
Australia.prevYearThird = "Valtteri Bottas"
Australia.prevYearThirdTeam = "Mercedes"
Australia.prevYearThirdDelta = "+11.250"
Australia.linkF1 = "https://www.formula1.com/en/championship/races/2018/Australia"
Australia.linkWikiCircuit = "https://en.wikipedia.org/wiki/Melbourne_Grand_Prix_Circuit"
Australia.linkWikiRace = "https://en.wikipedia.org/wiki/Australian_Grand_Prix"

#Add properties to the Bahrain weekend
Bahrain = Weekend("Bahrain")
Bahrain.fullTitle = "2018 FORMULA 1 GULF AIR BAHRAIN GRAND PRIX"
Bahrain.round = 2
Bahrain.racenr = 980
Bahrain.hubTime = datetime.datetime(currYear, 4, 5, 20, 00)
Bahrain.fp1Time = datetime.datetime(currYear, 4, 6, 11, 00)
Bahrain.fp2Time = datetime.datetime(currYear, 4, 6, 15, 00)
Bahrain.fp3Time = datetime.datetime(currYear, 4, 7, 12, 00)
Bahrain.qualiTime = datetime.datetime(currYear, 4, 7, 15, 00)
Bahrain.raceTime = datetime.datetime(currYear, 4, 8, 15, 10)
Bahrain.dadTime = datetime.datetime(currYear, 4, 9, 15, 00)
Bahrain.namean = "Bahrain"
Bahrain.flag = "#bh"
Bahrain.circuit = "Bahrain International Circuit"
Bahrain.city = "Sakhir"
Bahrain.weatherID = 290104
Bahrain.firstHeld = 2004
Bahrain.length = 5.412
Bahrain.laps = 57
Bahrain.distance = 308.238
Bahrain.poleLeft = True
Bahrain.lastYear = prevYear
Bahrain.lapRecordTime = "1:31.447"
Bahrain.lapRecordFlag = "#es"
Bahrain.lapRecordHolder = "Pedro de la Rosa"
Bahrain.lapRecordTeam = "McLaren"
Bahrain.lapRecordYear = 2005
Bahrain.prevYearPoleFlag = "#fi"
Bahrain.prevYearPoleHolder = "Valtteri Bottas"
Bahrain.prevYearPoleTeam = "Mercedes"
Bahrain.prevYearPoleTime = "1:28.769"
Bahrain.prevYearFastestFlag = "#gb"
Bahrain.prevYearFastestHolder = "Lewis Hamilton"
Bahrain.prevYearFastestTeam = "Mercedes"
Bahrain.prevYearFastestTime = "1:32.798"
Bahrain.prevYearWinnerFlag = "#de"
Bahrain.prevYearWinner = "Sebastian Vettel"
Bahrain.prevYearWinnerTeam = "Ferrari"
Bahrain.prevYearSecondFlag = "#gb"
Bahrain.prevYearSecond = "Lewis Hamilton"
Bahrain.prevYearSecondTeam = "Mercedes"
Bahrain.prevYearSecondDelta = "+6.660"
Bahrain.prevYearThirdFlag = "#fi"
Bahrain.prevYearThird = "Valtteri Bottas"
Bahrain.prevYearThirdTeam = "Mercedes"
Bahrain.prevYearThirdDelta = "+20.397"
Bahrain.linkF1 = "https://www.formula1.com/en/championship/races/2018/Bahrain"
Bahrain.linkWikiCircuit = "https://en.wikipedia.org/wiki/Bahrain_International_Circuit"
Bahrain.linkWikiRace = "https://en.wikipedia.org/wiki/Bahrain_Grand_Prix"

#Add properties to the China weekend
China = Weekend("China")
China.fullTitle = "2018 FORMULA 1 HEINEKEN CHINESE GRAND PRIX"
China.round = 3
China.racenr = 981
China.hubTime = datetime.datetime(currYear, 4, 12, 14, 00)
China.fp1Time = datetime.datetime(currYear, 4, 13, 2, 00)
China.fp2Time = datetime.datetime(currYear, 4, 13, 6, 00)
China.fp3Time = datetime.datetime(currYear, 4, 14, 3, 00)
China.qualiTime = datetime.datetime(currYear, 4, 14, 6, 00)
China.raceTime = datetime.datetime(currYear, 4, 15, 6, 10)
China.dadTime = datetime.datetime(currYear, 4, 16, 6, 00)
China.namean = "Chinese"
China.flag = "#cn"
China.circuit = "Shanghai International Circuit"
China.city = "Shanghai"
China.weatherID = 1796236
China.firstHeld = 2004
China.length = 5.451
China.laps = 56
China.distance = 305.066
China.poleLeft = True
China.lastYear = prevYear
China.lapRecordTime = "1:32.238"
China.lapRecordFlag = "#de"
China.lapRecordHolder = "Michael Schumacher"
China.lapRecordTeam = "Ferrari"
China.lapRecordYear = 2004
China.prevYearPoleFlag = "#gb"
China.prevYearPoleHolder = "Lewis Hamilton"
China.prevYearPoleTeam = "Mercedes"
China.prevYearPoleTime = "1:31.678"
China.prevYearFastestFlag = "#gb"
China.prevYearFastestHolder = "Lewis Hamilton"
China.prevYearFastestTeam = "Mercedes"
China.prevYearFastestTime = "1:35.378"
China.prevYearWinnerFlag = "#gb"
China.prevYearWinner = "Lewis Hamilton"
China.prevYearWinnerTeam = "Mercedes"
China.prevYearSecondFlag = "#de"
China.prevYearSecond = "Sebastian Vettel"
China.prevYearSecondTeam = "Ferrari"
China.prevYearSecondDelta = "+6.250"
China.prevYearThirdFlag = "#nl"
China.prevYearThird = "Max Verstappen"
China.prevYearThirdTeam = "Red Bull-TAG Heuer"
China.prevYearThirdDelta = "+45.192"
China.linkF1 = "https://www.formula1.com/en/championship/races/2018/China"
China.linkWikiCircuit = "https://en.wikipedia.org/wiki/Shanghai_International_Circuit"
China.linkWikiRace = "https://en.wikipedia.org/wiki/Chinese_Grand_Prix"

#Add properties to the Azerbaijan weekend
Azerbaijan = Weekend("Azerbaijan")
Azerbaijan.fullTitle = "2018 FORMULA 1 AZERBAIJAN GRAND PRIX"
Azerbaijan.round = 4
Azerbaijan.racenr = 982
Azerbaijan.hubTime = datetime.datetime(currYear, 4, 26, 2, 00)
Azerbaijan.fp1Time = datetime.datetime(currYear, 4, 27, 9, 00)
Azerbaijan.fp2Time = datetime.datetime(currYear, 4, 27, 13, 00)
Azerbaijan.fp3Time = datetime.datetime(currYear, 4, 28, 10, 00)
Azerbaijan.qualiTime = datetime.datetime(currYear, 4, 28, 13, 00)
Azerbaijan.raceTime = datetime.datetime(currYear, 4, 29, 12, 10)
Azerbaijan.dadTime = datetime.datetime(currYear, 4, 30, 12, 10)
Azerbaijan.namean = "Azerbaijan"
Azerbaijan.flag = "#az"
Azerbaijan.circuit = "Baku City Circuit"
Azerbaijan.city = "Baku"
Azerbaijan.weatherID = 587084
Azerbaijan.firstHeld = 2016
Azerbaijan.length = 6.003
Azerbaijan.laps = 51
Azerbaijan.distance = 306.049
Azerbaijan.poleLeft = False
Azerbaijan.lastYear = prevYear
Azerbaijan.lapRecordTime = "1:43.441"
Azerbaijan.lapRecordFlag = "#de"
Azerbaijan.lapRecordHolder = "Sebastian Vettel"
Azerbaijan.lapRecordTeam = "Ferrari"
Azerbaijan.lapRecordYear = 2017
Azerbaijan.prevYearPoleFlag = "#gb"
Azerbaijan.prevYearPoleHolder = "Lewis Hamilton"
Azerbaijan.prevYearPoleTeam = "Mercedes"
Azerbaijan.prevYearPoleTime = "1:40.593"
Azerbaijan.prevYearFastestFlag = "#de"
Azerbaijan.prevYearFastestHolder = "Sebastian Vettel"
Azerbaijan.prevYearFastestTeam = "Ferrari"
Azerbaijan.prevYearFastestTime = "1:43.441"
Azerbaijan.prevYearWinnerFlag = "#au"
Azerbaijan.prevYearWinner = "Daniel Ricciardo"
Azerbaijan.prevYearWinnerTeam = "Red Bull-TAG Heuer"
Azerbaijan.prevYearSecondFlag = "#fi"
Azerbaijan.prevYearSecond = "Valtteri Bottas"
Azerbaijan.prevYearSecondTeam = "Mercedes"
Azerbaijan.prevYearSecondDelta = "+3.904"
Azerbaijan.prevYearThirdFlag = "#ca"
Azerbaijan.prevYearThird = "Lance Stroll"
Azerbaijan.prevYearThirdTeam = "Williams-Mercedes"
Azerbaijan.prevYearThirdDelta = "+4.009"
Azerbaijan.linkF1 = "https://www.formula1.com/en/championship/races/2018/Azerbaijan"
Azerbaijan.linkWikiCircuit = "https://en.wikipedia.org/wiki/Baku_City_Circuit"
Azerbaijan.linkWikiRace = "https://en.wikipedia.org/wiki/Azerbaijan_Grand_Prix"

#Add properties to the Spain weekend
Spain = Weekend("Spain")
Spain.fullTitle = "FORMULA 1 GRAN PREMIO DE ESPAÑA PIRELLI 2018"
Spain.round = 5
Spain.racenr = 983
Spain.hubTime = datetime.datetime(currYear, 5, 10, 8, 00)
Spain.fp1Time = datetime.datetime(currYear, 5, 11, 9, 00)
Spain.fp2Time = datetime.datetime(currYear, 5, 11, 13, 00)
Spain.fp3Time = datetime.datetime(currYear, 5, 12, 10, 00)
Spain.qualiTime = datetime.datetime(currYear, 5, 12, 13, 00)
Spain.raceTime = datetime.datetime(currYear, 5, 13, 13, 10)
Spain.dadTime = datetime.datetime(currYear, 5, 14, 13, 00)
Spain.namean = "Spanish"
Spain.flag = "#es"
Spain.circuit = "Circuit de Barcelona-Catalunya"
Spain.city = "Barcelona"
Spain.weatherID = 3128760
Spain.firstHeld = 1913
Spain.length = 4.655
Spain.laps = 66
Spain.distance = 307.104
Spain.poleLeft = True
Spain.lastYear = prevYear
Spain.lapRecordTime = "1:21.670"
Spain.lapRecordFlag = "#fi"
Spain.lapRecordHolder = "Kimi Raikkonen"
Spain.lapRecordTeam = "Ferrari"
Spain.lapRecordYear = 2008
Spain.prevYearPoleFlag = "#gb"
Spain.prevYearPoleHolder = "Lewis Hamilton"
Spain.prevYearPoleTeam = "Mercedes"
Spain.prevYearPoleTime = "1:19.149"
Spain.prevYearFastestFlag = "#gb"
Spain.prevYearFastestHolder = "Lewis Hamilton"
Spain.prevYearFastestTeam = "Mercedes"
Spain.prevYearFastestTime = "1:23.593"
Spain.prevYearWinnerFlag = "#gb"
Spain.prevYearWinner = "Lewis Hamilton"
Spain.prevYearWinnerTeam = "Mercedes"
Spain.prevYearSecondFlag = "#de"
Spain.prevYearSecond = "Sebastian Vettel"
Spain.prevYearSecondTeam = "Ferrari"
Spain.prevYearSecondDelta = "+3.490"
Spain.prevYearThirdFlag = "#au"
Spain.prevYearThird = "Daniel Ricciardo"
Spain.prevYearThirdTeam = "Red Bull-TAG Heuer"
Spain.prevYearThirdDelta = "+1:15.820"
Spain.linkF1 = "https://www.formula1.com/en/championship/races/2018/Spain"
Spain.linkWikiCircuit = "https://en.wikipedia.org/wiki/Circuit_de_Barcelona-Catalunya"
Spain.linkWikiRace = "https://en.wikipedia.org/wiki/Spanish_Grand_Prix"

#Add properties to the Monaco weekend
Monaco = Weekend("Monaco")
Monaco.fullTitle = "FORMULA 1 GRAND PRIX DE MONACO 2018"
Monaco.round = 6
Monaco.racenr = 984
Monaco.hubTime = datetime.datetime(currYear, 5, 23, 14, 00)
Monaco.fp1Time = datetime.datetime(currYear, 5, 24, 9, 00)
Monaco.fp2Time = datetime.datetime(currYear, 5, 24, 13, 00)
Monaco.fp3Time = datetime.datetime(currYear, 5, 26, 10, 00)
Monaco.qualiTime = datetime.datetime(currYear, 5, 26, 13, 00)
Monaco.raceTime = datetime.datetime(currYear, 5, 27, 13, 10)
Monaco.dadTime = datetime.datetime(currYear, 5, 28, 13, 00)
Monaco.namean = "Monaco"
Monaco.flag = "#mc"
Monaco.circuit = "Circuit de Monaco"
Monaco.city = "Monte Carlo"
Monaco.weatherID = 2993458
Monaco.firstHeld = 1929
Monaco.length = 3.337
Monaco.laps = 78
Monaco.distance = 260.286
Monaco.poleLeft = False
Monaco.lastYear = prevYear
Monaco.lapRecordTime = "1:14.820"
Monaco.lapRecordFlag = "#mx"
Monaco.lapRecordHolder = "Sergio Pérez"
Monaco.lapRecordTeam = "Force India"
Monaco.lapRecordYear = 2017
Monaco.prevYearPoleFlag = "#fi"
Monaco.prevYearPoleHolder = "Kimi Räikkönen"
Monaco.prevYearPoleTeam = "Ferrari"
Monaco.prevYearPoleTime = "1:12.178"
Monaco.prevYearFastestFlag = "#mx"
Monaco.prevYearFastestHolder = "Sergio Pérez"
Monaco.prevYearFastestTeam = "Force India"
Monaco.prevYearFastestTime = "1:14.820"
Monaco.prevYearWinnerFlag = "#de"
Monaco.prevYearWinner = "Sebastian Vettel"
Monaco.prevYearWinnerTeam = "Ferrari"
Monaco.prevYearSecondFlag = "#fi"
Monaco.prevYearSecond = "Kimi Räikkönen"
Monaco.prevYearSecondTeam = "Ferrari"
Monaco.prevYearSecondDelta = "+3.145"
Monaco.prevYearThirdFlag = "#au"
Monaco.prevYearThird = "Daniel Ricciardo"
Monaco.prevYearThirdTeam = "Red Bull-TAG Heuer"
Monaco.prevYearThirdDelta = "+3.745"
Monaco.linkF1 = "https://www.formula1.com/en/championship/races/2018/Monaco"
Monaco.linkWikiCircuit = "https://en.wikipedia.org/wiki/Circuit_de_Monaco"
Monaco.linkWikiRace = "https://en.wikipedia.org/wiki/Monaco_Grand_Prix"

#Add properties to the Canada weekend
Canada = Weekend("Canada")
Canada.fullTitle = "FORMULA 1 GRAND PRIX DU CANADA 2018"
Canada.round = 7
Canada.racenr = 985
Canada.hubTime = datetime.datetime(currYear, 6, 7, 20, 00)
Canada.fp1Time = datetime.datetime(currYear, 6, 8, 14, 00)
Canada.fp2Time = datetime.datetime(currYear, 6, 8, 18, 00)
Canada.fp3Time = datetime.datetime(currYear, 6, 9, 15, 00)
Canada.qualiTime = datetime.datetime(currYear, 6, 9, 18, 00)
Canada.raceTime = datetime.datetime(currYear, 6, 10, 18, 10)
Canada.dadTime = datetime.datetime(currYear, 6, 11, 18, 00)
Canada.namean = "Canadian"
Canada.flag = "#ca"
Canada.circuit = "Circuit Gilles Villeneuve"
Canada.city = "Montreal"
Canada.weatherID = 6077243
Canada.firstHeld = 1961
Canada.length = 4.361
Canada.laps = 70
Canada.distance = 305.270
Canada.poleLeft = True
Canada.lastYear = prevYear
Canada.lapRecordTime = "1:13.622"
Canada.lapRecordFlag = "#br"
Canada.lapRecordHolder = "Rubens Barrichello"
Canada.lapRecordTeam = "Ferrari"
Canada.lapRecordYear = 2004
Canada.prevYearPoleFlag = "#gb"
Canada.prevYearPoleHolder = "Lewis Hamilton"
Canada.prevYearPoleTeam = "Mercedes"
Canada.prevYearPoleTime = "1:11.459"
Canada.prevYearFastestFlag = "#gb"
Canada.prevYearFastestHolder = "Lewis Hamilton"
Canada.prevYearFastestTeam = "Merdeces"
Canada.prevYearFastestTime = "1:14.551"
Canada.prevYearWinnerFlag = "#gb"
Canada.prevYearWinner = "Lewis Hamilton"
Canada.prevYearWinnerTeam = "Mercedes"
Canada.prevYearSecondFlag = "#fi"
Canada.prevYearSecond = "Valtteri Bottas"
Canada.prevYearSecondTeam = "Mercedes"
Canada.prevYearSecondDelta = "+19.783"
Canada.prevYearThirdFlag = "#au"
Canada.prevYearThird = "Daniel Ricciardo"
Canada.prevYearThirdTeam = "Red Bull-TAG Heuer"
Canada.prevYearThirdDelta = "+35.297"
Canada.linkF1 = "https://www.formula1.com/en/championship/races/2018/Canada"
Canada.linkWikiCircuit = "https://en.wikipedia.org/wiki/Circuit_Gilles_Villeneuve"
Canada.linkWikiRace = "https://en.wikipedia.org/wiki/Canadian_Grand_Prix"

#Add properties to the France weekend
France = Weekend("France")
France.fullTitle = "FORMULA 1 GRAND PRIX DE FRANCE 2018"
France.round = 8
France.racenr = 986
France.hubTime = datetime.datetime(currYear, 6, 21, 20, 00)
France.fp1Time = datetime.datetime(currYear, 6, 22, 10, 00)
France.fp2Time = datetime.datetime(currYear, 6, 22, 14, 00)
France.fp3Time = datetime.datetime(currYear, 6, 23, 11, 00)
France.qualiTime = datetime.datetime(currYear, 6, 23, 14, 00)
France.raceTime = datetime.datetime(currYear, 6, 24, 14, 10)
France.dadTime = datetime.datetime(currYear, 6, 25, 14, 00)
France.namean = "French"
France.flag = "#fr"
France.circuit = "Circuit Paul Ricard"
France.city = "Le Castellet"
France.weatherID = 3004838
France.firstHeld = 1906
France.length = 5.861
France.laps = 53
France.distance = 310.633
France.poleLeft = True
France.lastYear = "N/A"
France.lapRecordTime = "N/A"
France.lapRecordFlag = "#noflag"
France.lapRecordHolder = "N/A"
France.lapRecordTeam = "N/A"
France.lapRecordYear = "N/A"
France.prevYearPoleFlag = "#noflag"
France.prevYearPoleHolder = "N/A"
France.prevYearPoleTeam = "N/A"
France.prevYearPoleTime = "N/A"
France.prevYearFastestFlag = "#noflag"
France.prevYearFastestHolder = "N/A"
France.prevYearFastestTeam = "N/A"
France.prevYearFastestTime = "N/A"
France.prevYearWinnerFlag = "#noflag"
France.prevYearWinner = "N/A"
France.prevYearWinnerTeam = "N/A"
France.prevYearSecondFlag = "#noflag"
France.prevYearSecond = "N/A"
France.prevYearSecondTeam = "N/A"
France.prevYearSecondDelta = "N/A"
France.prevYearThirdFlag = "#noflag"
France.prevYearThird = "N/A"
France.prevYearThirdTeam = "N/A"
France.prevYearThirdDelta = "N/A"
France.linkF1 = "https://www.formula1.com/en/championship/races/2018/France"
France.linkWikiCircuit = "https://en.wikipedia.org/wiki/Circuit_Paul_Ricard"
France.linkWikiRace = "https://en.wikipedia.org/wiki/French_Grand_Prix"

#Add properties to the Austria weekend
Austria = Weekend("Austria")
Austria.fullTitle = "FORMULA 1 GROSSER PREIS VON ÖSTERREICH 2018"
Austria.round = 9
Austria.racenr = 987
Austria.hubTime = datetime.datetime(currYear, 6, 28, 8, 00)
Austria.fp1Time = datetime.datetime(currYear, 6, 29, 9, 00)
Austria.fp2Time = datetime.datetime(currYear, 6, 29, 13, 00)
Austria.fp3Time = datetime.datetime(currYear, 6, 30, 10, 00)
Austria.qualiTime = datetime.datetime(currYear, 6, 30, 13, 00)
Austria.raceTime = datetime.datetime(currYear, 7, 1, 13, 10)
Austria.dadTime = datetime.datetime(currYear, 7, 2, 13, 00)
Austria.namean = "Austrian"
Austria.flag = "#at"
Austria.circuit = "Red Bull Ring"
Austria.city = "Spielberg"
Austria.weatherID = 2773887
Austria.firstHeld = 1963
Austria.length = 4.318
Austria.laps = 71
Austria.distance = 307.146
Austria.poleLeft = True
Austria.lastYear = prevYear
Austria.lapRecordTime = "1:07.411"
Austria.lapRecordFlag = "#gb"
Austria.lapRecordHolder = "Lewis Hamilton"
Austria.lapRecordTeam = "Mercedes"
Austria.lapRecordYear = 2017
Austria.prevYearPoleFlag = "#fi"
Austria.prevYearPoleHolder = "Valtteri Bottas"
Austria.prevYearPoleTeam = "Mercedes"
Austria.prevYearPoleTime = "1:04.251"
Austria.prevYearFastestFlag = "#gb"
Austria.prevYearFastestHolder = "Lewis Hamilton"
Austria.prevYearFastestTeam = "Mercedes"
Austria.prevYearFastestTime = "1:07.411"
Austria.prevYearWinnerFlag = "#fi"
Austria.prevYearWinner = "Valtteri Bottas"
Austria.prevYearWinnerTeam = "Mercedes"
Austria.prevYearSecondFlag = "#de"
Austria.prevYearSecond = "Sebastian Vettel"
Austria.prevYearSecondTeam = "Ferrari"
Austria.prevYearSecondDelta = "+0.658"
Austria.prevYearThirdFlag = "#au"
Austria.prevYearThird = "Daniel Ricciardo"
Austria.prevYearThirdTeam = "Red Bull-TAG Heuer"
Austria.prevYearThirdDelta = "+6.012"
Austria.linkF1 = "https://www.formula1.com/en/championship/races/2018/Austria"
Austria.linkWikiCircuit = "https://en.wikipedia.org/wiki/Red_Bull_Ring"
Austria.linkWikiRace = "https://en.wikipedia.org/wiki/Austrian_Grand_Prix"

#Add properties to the Britain weekend
Britain = Weekend("Great Britain")
Britain.fullTitle = "2018 FORMULA 1 ROLEX BRITISH GRAND PRIX"
Britain.round = 10
Britain.round = 988
Britain.hubTime = datetime.datetime(currYear, 7, 5, 22, 00)
Britain.fp1Time = datetime.datetime(currYear, 7, 6, 9, 00)
Britain.fp2Time = datetime.datetime(currYear, 7, 6, 13, 00)
Britain.fp3Time = datetime.datetime(currYear, 7, 7, 10, 00)
Britain.qualiTime = datetime.datetime(currYear, 7, 7, 13, 00)
Britain.raceTime = datetime.datetime(currYear, 7, 8, 13, 10)
Britain.dadTime = datetime.datetime(currYear, 7, 9, 13, 00)
Britain.namean = "British"
Britain.flag = "#gb"
Britain.circuit = "Silverstone Circuit"
Britain.city = "Silverstone"
Britain.weatherID = 2642465
Britain.firstHeld = 1926
Britain.length = 5.891
Britain.laps = 52
Britain.distance = 306.291
Britain.poleLeft = True
Britain.lastYear = prevYear
Britain.lapRecordTime = "1:30.621"
Britain.lapRecordFlag = "#gb"
Britain.lapRecordHolder = "Lewis Hamilton"
Britain.lapRecordTeam = "Mercedes"
Britain.lapRecordYear = 2017
Britain.prevYearPoleFlag = "#gb"
Britain.prevYearPoleHolder = "Lewis Hamilton"
Britain.prevYearPoleTeam = "Mercedes"
Britain.prevYearPoleTime = "1:26.600"
Britain.prevYearFastestFlag = "#gb"
Britain.prevYearFastestHolder = "Lewis Hamilton"
Britain.prevYearFastestTeam = "Merdeces"
Britain.prevYearFastestTime = "1:30.621"
Britain.prevYearWinnerFlag = "#gb"
Britain.prevYearWinner = "Lewis Hamilton"
Britain.prevYearWinnerTeam = "Mercedes"
Britain.prevYearSecondFlag = "#fi"
Britain.prevYearSecond = "Valtteri Bottas"
Britain.prevYearSecondTeam = "Mercedes"
Britain.prevYearSecondDelta = "+14.063"
Britain.prevYearThirdFlag = "#fi"
Britain.prevYearThird = "Kimi Räikkönen"
Britain.prevYearThirdTeam = "Ferrari"
Britain.prevYearThirdDelta = "+36.570"
Britain.linkF1 = "https://www.formula1.com/en/championship/races/2018/Great_Britain"
Britain.linkWikiCircuit = "https://en.wikipedia.org/wiki/Silverstone_Circuit"
Britain.linkWikiRace = "https://en.wikipedia.org/wiki/British_Grand_Prix"

#Add properties to the Germany weekend
Germany = Weekend("Germany")
Germany.fullTitle = "FORMULA 1 GROSSER PREIS VON DEUTSCHLAND 2018"
Germany.round = 11
Germany.round = 989
Germany.hubTime = datetime.datetime(currYear, 7, 19, 22, 00)
Germany.fp1Time = datetime.datetime(currYear, 7, 20, 9, 00)
Germany.fp2Time = datetime.datetime(currYear, 7, 20, 13, 00)
Germany.fp3Time = datetime.datetime(currYear, 7, 21, 10, 00)
Germany.qualiTime = datetime.datetime(currYear, 7, 21, 13, 00)
Germany.raceTime = datetime.datetime(currYear, 7, 22, 13, 10)
Germany.dadTime = datetime.datetime(currYear, 7, 23, 13, 00)
Germany.namean = "German"
Germany.flag = "#de"
Germany.circuit = "Hockenheimring"
Germany.city = "Hockenheim"
Germany.weatherID = 2902852
Germany.firstHeld = 1926
Germany.length = 4.574
Germany.laps = 67
Germany.distance = 306.442
Germany.poleLeft = True
Germany.lastYear = 2016
Germany.lapRecordTime = "1:13.780"
Germany.lapRecordFlag = "#fi"
Germany.lapRecordHolder = "Kimi Räikkönen"
Germany.lapRecordTeam = "McLaren"
Germany.lapRecordYear = 2004
Germany.prevYearPoleFlag = "#de"
Germany.prevYearPoleHolder = "Nico Rosberg"
Germany.prevYearPoleTeam = "Mercedes"
Germany.prevYearPoleTime = "1:14.363"
Germany.prevYearFastestFlag = "#au"
Germany.prevYearFastestHolder = "Daniel Ricciardo"
Germany.prevYearFastestTeam = "Red Bull-TAG Heuer"
Germany.prevYearFastestTime = "1:18.442"
Germany.prevYearWinnerFlag = "#gb"
Germany.prevYearWinner = "Lewis Hamilton"
Germany.prevYearWinnerTeam = "Mercedes"
Germany.prevYearSecondFlag = "#au"
Germany.prevYearSecond = "Daniel Ricciardo"
Germany.prevYearSecondTeam = "Red Bull-TAG Heuer"
Germany.prevYearSecondDelta = "+6.996"
Germany.prevYearThirdFlag = "#nl"
Germany.prevYearThird = "Max Verstappen"
Germany.prevYearThirdTeam = "Red Bull-TAG Heuer"
Germany.prevYearThirdDelta = "+13.413"
Germany.linkF1 = "https://www.formula1.com/en/championship/races/2018/Germany"
Germany.linkWikiCircuit = "https://en.wikipedia.org/wiki/Hockenheimring"
Germany.linkWikiRace = "https://en.wikipedia.org/wiki/German_Grand_Prix"

#Add properties to the Hungary weekend
Hungary = Weekend("Hungary")
Hungary.fullTitle = "FORMULA 1 PIRELLI MAGYAR NAGYDÍJ 2018"
Hungary.round = 12
Hungary.racenr = 990
Hungary.hubTime = datetime.datetime(currYear, 7, 27, 20, 00)
Hungary.fp1Time = datetime.datetime(currYear, 7, 28, 9, 00)
Hungary.fp2Time = datetime.datetime(currYear, 7, 28, 13, 00)
Hungary.fp3Time = datetime.datetime(currYear, 7, 29, 10, 00)
Hungary.qualiTime = datetime.datetime(currYear, 7, 29, 13, 00)
Hungary.raceTime = datetime.datetime(currYear, 7, 30, 13, 10)
Hungary.dadTime = datetime.datetime(currYear, 7, 31, 13, 00)
Hungary.namean = "Hungarian"
Hungary.flag = "#hu"
Hungary.circuit = "Hungaroring"
Hungary.city = "Budapest"
Hungary.weatherID = 3054643
Hungary.firstHeld = 1936
Hungary.length = 4.381
Hungary.laps = 70
Hungary.distance = 306.663
Hungary.poleLeft = True
Hungary.lastYear = prevYear
Hungary.lapRecordTime = "1:19.071"
Hungary.lapRecordFlag = "#de"
Hungary.lapRecordHolder = "Michael Schumacher"
Hungary.lapRecordTeam = "Ferrari"
Hungary.lapRecordYear = 2004
Hungary.prevYearPoleFlag = "#de"
Hungary.prevYearPoleHolder = "Sebastian Vettel"
Hungary.prevYearPoleTeam = "Ferrari"
Hungary.prevYearPoleTime = "1:16.276"
Hungary.prevYearFastestFlag = "#es"
Hungary.prevYearFastestHolder = "Fernando Alonso"
Hungary.prevYearFastestTeam = "McLaren-Honda"
Hungary.prevYearFastestTime = "1:20.182"
Hungary.prevYearWinnerFlag = "#de"
Hungary.prevYearWinner = "Sebastian Vettel"
Hungary.prevYearWinnerTeam = "Ferrari"
Hungary.prevYearSecondFlag = "#fi"
Hungary.prevYearSecond = "Kimi Räikkönen"
Hungary.prevYearSecondTeam = "Ferrari"
Hungary.prevYearSecondDelta = "+0.908"
Hungary.prevYearThirdFlag = "#fi"
Hungary.prevYearThird = "Valtteri Bottas"
Hungary.prevYearThirdTeam = "Mercedes"
Hungary.prevYearThirdDelta = "+12.462"
Hungary.linkF1 = "https://www.formula1.com/en/championship/races/2018/Hungary"
Hungary.linkWikiCircuit = "https://en.wikipedia.org/wiki/Hungaroring"
Hungary.linkWikiRace = "https://en.wikipedia.org/wiki/Hungarian_Grand_Prix"

#Add properties to the Belgium weekend
Belgium = Weekend("Belgium")
Belgium.fullTitle = "2018 FORMULA 1 BELGIAN GRAND PRIX"
Belgium.round = 13
Belgium.racenr = 991
Belgium.hubTime = datetime.datetime(currYear, 8, 23, 2, 00)
Belgium.fp1Time = datetime.datetime(currYear, 8, 24, 9, 00)
Belgium.fp2Time = datetime.datetime(currYear, 8, 24, 13, 00)
Belgium.fp3Time = datetime.datetime(currYear, 8, 25, 10, 00)
Belgium.qualiTime = datetime.datetime(currYear, 8, 25, 13, 00)
Belgium.raceTime = datetime.datetime(currYear, 8, 26, 13, 10)
Belgium.dadTime = datetime.datetime(currYear, 8, 27, 13, 00)
Belgium.namean = "Belgian"
Belgium.flag = "#be"
Belgium.circuit = "Circuit de Spa-Francorchamps"
Belgium.city = "Spa-Francorchamps"
Belgium.weatherID = 2791834
Belgium.firstHeld = 1925
Belgium.length = 7.004
Belgium.laps = 44
Belgium.distance = 308.052
Belgium.poleLeft = False
Belgium.lastYear = prevYear
Belgium.lapRecordTime = "1:46.577"
Belgium.lapRecordFlag = "#de"
Belgium.lapRecordHolder = "Sebastial Vettel"
Belgium.lapRecordTeam = "Ferrari"
Belgium.lapRecordYear = 2017
Belgium.prevYearPoleFlag = "#gb"
Belgium.prevYearPoleHolder = "Lewis Hamilton"
Belgium.prevYearPoleTeam = "Mercedes"
Belgium.prevYearPoleTime = "1:42.553"
Belgium.prevYearFastestFlag = "#de"
Belgium.prevYearFastestHolder = "Sebastian Vettel"
Belgium.prevYearFastestTeam = "Ferraro"
Belgium.prevYearFastestTime = "1:46.577"
Belgium.prevYearWinnerFlag = "#gb"
Belgium.prevYearWinner = "Lewis Hamilton"
Belgium.prevYearWinnerTeam = "Mercedes"
Belgium.prevYearSecondFlag = "#de"
Belgium.prevYearSecond = "Sebastian Vettel"
Belgium.prevYearSecondTeam = "Ferrari"
Belgium.prevYearSecondDelta = "+2.358"
Belgium.prevYearThirdFlag = "#au"
Belgium.prevYearThird = "Daniel Ricciardo"
Belgium.prevYearThirdTeam = "Red Bull-TAG Heuer"
Belgium.prevYearThirdDelta = "+10.791"
Belgium.linkF1 = "https://www.formula1.com/en/championship/races/2018/Belgium"
Belgium.linkWikiCircuit = "https://en.wikipedia.org/wiki/Circuit_de_Spa-Francorchamps"
Belgium.linkWikiRace = "https://en.wikipedia.org/wiki/Belgian_Grand_Prix"

#Add properties to the Italy weekend
Italy = Weekend("Italy")
Italy.fullTitle = "FORMULA 1 GRAN PREMIO HEINEKEN D'ITALIA 2018"
Italy.round = 14
Italy.racenr = 992
Italy.hubTime = datetime.datetime(currYear, 8, 30, 8, 00)
Italy.fp1Time = datetime.datetime(currYear, 8, 31, 9, 00)
Italy.fp2Time = datetime.datetime(currYear, 8, 31, 13, 00)
Italy.fp3Time = datetime.datetime(currYear, 9, 1, 10, 00)
Italy.qualiTime = datetime.datetime(currYear, 9, 1, 13, 00)
Italy.raceTime = datetime.datetime(currYear, 9, 2, 13, 10)
Italy.dadTime = datetime.datetime(currYear, 9, 3, 13, 00)
Italy.namean = "Italian"
Italy.flag = "#it"
Italy.circuit = "Autodromo Nazionale Monza"
Italy.city = "Monza"
Italy.weatherID = 3172629
Italy.firstHeld = 1921
Italy.length = 5.793
Italy.laps = 53
Italy.distance = 306.720
Italy.poleLeft = True
Italy.lastYear = prevYear
Italy.lapRecordTime = "1:21.046"
Italy.lapRecordFlag = "#br"
Italy.lapRecordHolder = "Rubens Barrichello"
Italy.lapRecordTeam = "Ferrari"
Italy.lapRecordYear = 2004
Italy.prevYearPoleFlag = "#gb"
Italy.prevYearPoleHolder = "Lewis Hamilton"
Italy.prevYearPoleTeam = "Mercedes"
Italy.prevYearPoleTime = "1:35.554"
Italy.prevYearFastestFlag = "#au"
Italy.prevYearFastestHolder = "Daniel Ricciardo"
Italy.prevYearFastestTeam = "Red Bull-TAG Heuer"
Italy.prevYearFastestTime = "1:23.361"
Italy.prevYearWinnerFlag = "#gb"
Italy.prevYearWinner = "Lewis Hamilton"
Italy.prevYearWinnerTeam = "Mercedes"
Italy.prevYearSecondFlag = "#fi"
Italy.prevYearSecond = "Valtteri Bottas"
Italy.prevYearSecondTeam = "Mercedes"
Italy.prevYearSecondDelta = "+4.471"
Italy.prevYearThirdFlag = "#de"
Italy.prevYearThird = "Sebastian Vettel"
Italy.prevYearThirdTeam = "Ferrari"
Italy.prevYearThirdDelta = "+36.317"
Italy.linkF1 = "https://www.formula1.com/en/championship/races/2018/Italy"
Italy.linkWikiCircuit = "https://en.wikipedia.org/wiki/Autodromo_Nazionale_Monza"
Italy.linkWikiRace = "https://en.wikipedia.org/wiki/Italian_Grand_Prix"

#Add properties to the Singapore weekend
Singapore = Weekend("Singapore")
Singapore.fullTitle = "2018 FORMULA 1 SINGAPORE GRAND PRIX"
Singapore.round = 15
Singapore.racenr = 993
Singapore.hubTime = datetime.datetime(currYear, 9, 13, 14, 00)
Singapore.fp1Time = datetime.datetime(currYear, 9, 14, 8, 30)
Singapore.fp2Time = datetime.datetime(currYear, 9, 14, 12, 30)
Singapore.fp3Time = datetime.datetime(currYear, 9, 15, 10, 00)
Singapore.qualiTime = datetime.datetime(currYear, 9, 15, 13, 00)
Singapore.raceTime = datetime.datetime(currYear, 9, 16, 12, 10)
Singapore.dadTime = datetime.datetime(currYear, 9, 17, 12, 00)
Singapore.namean = "Singapore"
Singapore.flag = "#sg"
Singapore.circuit = "Marina Bay Street Circuit"
Singapore.city = "Singapore"
Singapore.weatherID = 1880252
Singapore.firstHeld = 1966
Singapore.length = 5.065
Singapore.laps = 61
Singapore.distance = 308.828
Singapore.poleLeft = False
Singapore.lastYear = prevYear
Singapore.lapRecordTime = "1:45.008"
Singapore.lapRecordFlag = "#gb"
Singapore.lapRecordHolder = "Lewis Hamilton"
Singapore.lapRecordTeam = "Mercedes"
Singapore.lapRecordYear = 2017
Singapore.prevYearPoleFlag = "#de"
Singapore.prevYearPoleHolder = "Sebastian Vettel"
Singapore.prevYearPoleTeam = "Ferrari"
Singapore.prevYearPoleTime = "1:39.491"
Singapore.prevYearFastestFlag = "#gb"
Singapore.prevYearFastestHolder = "Lewis Hamilton"
Singapore.prevYearFastestTeam = "Mercedes"
Singapore.prevYearFastestTime = "1:45.008"
Singapore.prevYearWinnerFlag = "#gb"
Singapore.prevYearWinner = "Lewis Hamilton"
Singapore.prevYearWinnerTeam = "Mercedes"
Singapore.prevYearSecondFlag = "#au"
Singapore.prevYearSecond = "Daniel Ricciardo"
Singapore.prevYearSecondTeam = "Red Bull-TAG Heuer"
Singapore.prevYearSecondDelta = "+4.507"
Singapore.prevYearThirdFlag = "#fi"
Singapore.prevYearThird = "Valtteri Bottas"
Singapore.prevYearThirdTeam = "Mercedes"
Singapore.prevYearThirdDelta = "+8.800"
Singapore.linkF1 = "https://www.formula1.com/en/championship/races/2018/Singapore"
Singapore.linkWikiCircuit = "https://en.wikipedia.org/wiki/Marina_Bay_Street_Circuit"
Singapore.linkWikiRace = "https://en.wikipedia.org/wiki/Singapore_Grand_Prix"

#Add properties to the Russia weekend
Russia = Weekend("Russia")
Russia.fullTitle = "2018 FORMULA 1 VTB RUSSIAN GRAND PRIX"
Russia.round = 16
Russia.racenr = 994
Russia.hubTime = datetime.datetime(currYear, 9, 27, 20, 00)
Russia.fp1Time = datetime.datetime(currYear, 9, 28, 8, 00)
Russia.fp2Time = datetime.datetime(currYear, 9, 28, 12, 00)
Russia.fp3Time = datetime.datetime(currYear, 9, 29, 9, 00)
Russia.qualiTime = datetime.datetime(currYear, 9, 29, 12, 00)
Russia.raceTime = datetime.datetime(currYear, 9, 30, 12, 00)
Russia.dadTime = datetime.datetime(currYear, 10, 1, 12, 00)
Russia.namean = "Russian"
Russia.flag = "#ru"
Russia.circuit = "Sochi Autodrom"
Russia.city = "Sochi"
Russia.weatherID = 491422
Russia.firstHeld = 1913
Russia.length = 5.838
Russia.laps = 53
Russia.distance = 309.732
Russia.poleLeft = True
Russia.lastYear = prevYear
Russia.lapRecordTime = "1:36.844"
Russia.lapRecordFlag = "#fi"
Russia.lapRecordHolder = "Kimi Räikkonen"
Russia.lapRecordTeam = "Ferrari"
Russia.lapRecordYear = 2017
Russia.prevYearPoleFlag = "#de"
Russia.prevYearPoleHolder = "Sebastian Vettel"
Russia.prevYearPoleTeam = "Ferrari"
Russia.prevYearPoleTime = "1:33.194"
Russia.prevYearFastestFlag = "#fi"
Russia.prevYearFastestHolder = "Kimi Räikkönen"
Russia.prevYearFastestTeam = "Ferrari"
Russia.prevYearFastestTime = "1:36.844"
Russia.prevYearWinnerFlag = "#fi"
Russia.prevYearWinner = "Valtteri Bottas"
Russia.prevYearWinnerTeam = "Mercedes"
Russia.prevYearSecondFlag = "#de"
Russia.prevYearSecond = "Sebastian Vettel"
Russia.prevYearSecondTeam = "Ferrari"
Russia.prevYearSecondDelta = "+0.617"
Russia.prevYearThirdFlag = "#fi"
Russia.prevYearThird = "Kimi Räikkönen"
Russia.prevYearThirdTeam = "Ferrari"
Russia.prevYearThirdDelta = "+11.000"
Russia.linkF1 = "https://www.formula1.com/en/championship/races/2018/Russia"
Russia.linkWikiCircuit = "https://en.wikipedia.org/wiki/Sochi_Autodrom"
Russia.linkWikiRace = "https://en.wikipedia.org/wiki/Russian_Grand_Prix"

#Add properties to the Japan weekend
Japan = Weekend("Japan")
Japan.fullTitle = "2018 FORMULA 1 JAPANESE GRAND PRIX"
Japan.round = 17
Japan.racenr = 995
Japan.hubTime = datetime.datetime(currYear, 10, 4, 8, 00)
Japan.fp1Time = datetime.datetime(currYear, 10, 5, 1, 00)
Japan.fp2Time = datetime.datetime(currYear, 10, 5, 5, 00)
Japan.fp3Time = datetime.datetime(currYear, 10, 6, 3, 00)
Japan.qualiTime = datetime.datetime(currYear, 10, 6, 6, 00)
Japan.raceTime = datetime.datetime(currYear, 10, 7, 5, 10)
Japan.dadTime = datetime.datetime(currYear, 10, 8, 5, 00)
Japan.namean = "Japanese"
Japan.flag = "#jp"
Japan.circuit = "Suzuka International Racing Course"
Japan.city = "Suzuka"
Japan.weatherID = 1851348
Japan.firstHeld = 1963
Japan.length = 5.807
Japan.laps = 53
Japan.distance = 307.573
Japan.poleLeft = True
Japan.lastYear = prevYear
Japan.lapRecordTime = "1:31.540"
Japan.lapRecordFlag = "#gb"
Japan.lapRecordHolder = "Lewis Hamilton"
Japan.lapRecordTeam = "Mercedes"
Japan.lapRecordYear = 2017
Japan.prevYearPoleFlag = "#gb"
Japan.prevYearPoleHolder = "Lewis Hamilton"
Japan.prevYearPoleTeam = "Mercedes"
Japan.prevYearPoleTime = "1:27.319"
Japan.prevYearFastestFlag = "#fi"
Japan.prevYearFastestHolder = "Valtteri Bottas"
Japan.prevYearFastestTeam = "Mercedes"
Japan.prevYearFastestTime = "1:33.144"
Japan.prevYearWinnerFlag = "#gb"
Japan.prevYearWinner = "Lewis Hamilton"
Japan.prevYearWinnerTeam = "Mercedes"
Japan.prevYearSecondFlag = "#nl"
Japan.prevYearSecond = "Max Verstappen"
Japan.prevYearSecondTeam = "Red Bull-TAG Heuer"
Japan.prevYearSecondDelta = "+1.211"
Japan.prevYearThirdFlag = "#au"
Japan.prevYearThird = "Daniel Ricciardo"
Japan.prevYearThirdTeam = "Red Bull-TAG Heuer"
Japan.prevYearThirdDelta = "+9.679"
Japan.linkF1 = "https://www.formula1.com/en/championship/races/2018/Japan"
Japan.linkWikiCircuit = "https://en.wikipedia.org/wiki/Suzuka_Circuit"
Japan.linkWikiRace = "https://en.wikipedia.org/wiki/Japanese_Grand_Prix"

#Add properties to the United States weekend
US = Weekend("United States")
US.fullTitle = "2018 FORMULA 1 UNITED STATES GRAND PRIX"
US.round = 18
US.racenr = 996
US.hubTime = datetime.datetime(currYear, 10, 18, 14, 00)
US.fp1Time = datetime.datetime(currYear, 10, 19, 15, 00)
US.fp2Time = datetime.datetime(currYear, 10, 19, 19, 00)
US.fp3Time = datetime.datetime(currYear, 10, 20, 18, 00)
US.qualiTime = datetime.datetime(currYear, 10, 20, 21, 00)
US.raceTime = datetime.datetime(currYear, 10, 21, 19, 00)
US.dadTime = datetime.datetime(currYear, 10, 22, 19, 00)
US.namean = "United States"
US.flag = "#us"
US.circuit = "Circuit of the Americas"
US.city = "Austin"
US.weatherID = 5016884
US.firstHeld = 1908
US.length = 5.513
US.laps = 56
US.distance = 308.896
US.poleLeft = False
US.lastYear = prevYear
US.lapRecordTime = "1:37.766"
US.lapRecordFlag = "#de"
US.lapRecordHolder = "Sebastian Vettel"
US.lapRecordTeam = "Ferrari"
US.lapRecordYear = 2017
US.prevYearPoleFlag = "#gb"
US.prevYearPoleHolder = "Lewis Hamilton"
US.prevYearPoleTeam = "Mercedes"
US.prevYearPoleTime = "1:33.108"
US.prevYearFastestFlag = "#de"
US.prevYearFastestHolder = "Sebastial Vettel"
US.prevYearFastestTeam = "Ferrari"
US.prevYearFastestTime = "1:37.766"
US.prevYearWinnerFlag = "#gb"
US.prevYearWinner = "Lewis Hamilton"
US.prevYearWinnerTeam = "Mercedes"
US.prevYearSecondFlag = "#de"
US.prevYearSecond = "Sebastian Vettel"
US.prevYearSecondTeam = "Ferrari"
US.prevYearSecondDelta = "+10.143"
US.prevYearThirdFlag = "#fi"
US.prevYearThird = "Kimi Räikkönen"
US.prevYearThirdTeam = "Ferrari"
US.prevYearThirdDelta = "+15.779"
US.linkF1 = "https://www.formula1.com/en/championship/races/2018/United_States"
US.linkWikiCircuit = "https://en.wikipedia.org/wiki/Circuit_of_the_Americas"
US.linkWikiRace = "https://en.wikipedia.org/wiki/United_States_Grand_Prix"

#Add properties to the Mexico weekend
Mexico = Weekend("Mexico")
Mexico.fullTitle = "FORMULA 1 GRAN PREMIO DE MÉXICO 2018"
Mexico.round = 19
Mexico.racenr = 997
Mexico.hubTime = datetime.datetime(currYear, 10, 25, 20, 00)
Mexico.fp1Time = datetime.datetime(currYear, 10, 26, 15, 00)
Mexico.fp2Time = datetime.datetime(currYear, 10, 26, 19, 00)
Mexico.fp3Time = datetime.datetime(currYear, 10, 27, 15, 00)
Mexico.qualiTime = datetime.datetime(currYear, 10, 27, 18, 00)
Mexico.raceTime = datetime.datetime(currYear, 10, 28, 19, 10)
Mexico.dadTime = datetime.datetime(currYear, 10, 29, 15, 00)
Mexico.namean = "Mexican"
Mexico.flag = "#mx"
Mexico.circuit = "Autódromo Hermanos Rodríguez"
Mexico.city = "Mexico City"
Mexico.weatherID = 3530597
Mexico.firstHeld = 1962
Mexico.length = 4.304
Mexico.laps = 71
Mexico.distance = 305.541
Mexico.poleLeft = True
Mexico.lastYear = prevYear
Mexico.lapRecordTime = "1:18.785"
Mexico.lapRecordFlag = "#de"
Mexico.lapRecordHolder = "Sebastian Vettel"
Mexico.lapRecordTeam = "Ferrari"
Mexico.lapRecordYear = 2017
Mexico.prevYearPoleFlag = "#de"
Mexico.prevYearPoleHolder = "Sebastian Vettel"
Mexico.prevYearPoleTeam = "Ferrari"
Mexico.prevYearPoleTime = "1:16.488"
Mexico.prevYearFastestFlag = "#de"
Mexico.prevYearFastestHolder = "Sebastian Vettel"
Mexico.prevYearFastestTeam = "Ferrari"
Mexico.prevYearFastestTime = "1:18.785"
Mexico.prevYearWinnerFlag = "#nl"
Mexico.prevYearWinner = "Max Verstappen"
Mexico.prevYearWinnerTeam = "Red Bull-TAG Heuer"
Mexico.prevYearSecondFlag = "#fi"
Mexico.prevYearSecond = "Valtteri Bottas"
Mexico.prevYearSecondTeam = "Mercedes"
Mexico.prevYearSecondDelta = "+19.679"
Mexico.prevYearThirdFlag = "#fi"
Mexico.prevYearThird = "Kimi Räikkönen"
Mexico.prevYearThirdTeam = "Ferrari"
Mexico.prevYearThirdDelta = "+54.007"
Mexico.linkF1 = "https://www.formula1.com/en/championship/races/2018/Mexico"
Mexico.linkWikiCircuit = "https://en.wikipedia.org/wiki/Aut%C3%B3dromo_Hermanos_Rodr%C3%ADguez"
Mexico.linkWikiRace = "https://en.wikipedia.org/wiki/Mexican_Grand_Prix"

#Add properties to the Brazil weekend
Brazil = Weekend("Brazil")
Brazil.fullTitle = "FORMULA 1 GRANDE PRÊMIO DO BRASIL 2018"
Brazil.round = 20
Brazil.racenr = 998
Brazil.hubTime = datetime.datetime(currYear, 11, 8, 2, 00)
Brazil.fp1Time = datetime.datetime(currYear, 11, 9, 14, 00)
Brazil.fp2Time = datetime.datetime(currYear, 11, 9, 18, 00)
Brazil.fp3Time = datetime.datetime(currYear, 11, 10, 15, 00)
Brazil.qualiTime = datetime.datetime(currYear, 11, 10, 18, 00)
Brazil.raceTime = datetime.datetime(currYear, 11, 11, 18, 10)
Brazil.dadTime = datetime.datetime(currYear, 11, 12, 12, 00)
Brazil.namean = "Brazilian"
Brazil.flag = "#br"
Brazil.circuit = "Autódromo José Carlos Pace"
Brazil.city = "São Paulo"
Brazil.weatherID = 3448439
Brazil.firstHeld = 1972
Brazil.length = 4.309
Brazil.laps = 71
Brazil.distance = 305.909
Brazil.poleLeft = False
Brazil.lastYear = prevYear
Brazil.lapRecordTime = "1:11.044"
Brazil.lapRecordFlag = "#nl"
Brazil.lapRecordHolder = "Max Verstappen"
Brazil.lapRecordTeam = "Red Bull-TAG Heuer"
Brazil.lapRecordYear = 2017
Brazil.prevYearPoleFlag = "#fi"
Brazil.prevYearPoleHolder = "Valtteri Bottas"
Brazil.prevYearPoleTeam = "Mercedes"
Brazil.prevYearPoleTime = "1:08.322"
Brazil.prevYearFastestFlag = "#nl"
Brazil.prevYearFastestHolder = "Max Verstappen"
Brazil.prevYearFastestTeam = "Red Bull-TAG Heuer"
Brazil.prevYearFastestTime = "1:11.044"
Brazil.prevYearWinnerFlag = "#de"
Brazil.prevYearWinner = "Sebastian Vettel"
Brazil.prevYearWinnerTeam = "Ferrari"
Brazil.prevYearSecondFlag = "#fi"
Brazil.prevYearSecond = "Valtteri Bottas"
Brazil.prevYearSecondTeam = "Mercedes"
Brazil.prevYearSecondDelta = "+2.762"
Brazil.prevYearThirdFlag = "#fi"
Brazil.prevYearThird = "Kimi Räikkönen"
Brazil.prevYearThirdTeam = "Ferrari"
Brazil.prevYearThirdDelta = "+4.600"
Brazil.linkF1 = "https://www.formula1.com/en/championship/races/2018/Brazil"
Brazil.linkWikiCircuit = "https://en.wikipedia.org/wiki/Aut%C3%B3dromo_Jos%C3%A9_Carlos_Pace"
Brazil.linkWikiRace = "https://en.wikipedia.org/wiki/Brazilian_Grand_Prix"

#Add properties to the Abu Dhabi weekend
AbuDhabi = Weekend("United Arab Emirates")
AbuDhabi.fullTitle = "2018 FORMULA 1 ETIHAD AIRWAYS ABU DHABI GRAND PRIX"
AbuDhabi.round = 21
AbuDhabi.racenr = 999
AbuDhabi.hubTime = datetime.datetime(currYear, 11, 22, 8, 00)
AbuDhabi.fp1Time = datetime.datetime(currYear, 11, 23, 9, 00)
AbuDhabi.fp2Time = datetime.datetime(currYear, 11, 23, 13, 00)
AbuDhabi.fp3Time = datetime.datetime(currYear, 11, 24, 10, 00)
AbuDhabi.qualiTime = datetime.datetime(currYear, 11, 24, 13, 00)
AbuDhabi.raceTime = datetime.datetime(currYear, 11, 25, 13, 10)
AbuDhabi.dadTime = datetime.datetime(currYear, 11, 26, 13, 00)
AbuDhabi.namean = "Abu Dhabi"
AbuDhabi.flag = "#ae"
AbuDhabi.circuit = "Yas Marina Circuit"
AbuDhabi.city = "Abu Dhabi"
AbuDhabi.weatherID = 292968
AbuDhabi.firstHeld = 2009
AbuDhabi.length = 5.554
AbuDhabi.laps = 55
AbuDhabi.distance = 305.470
AbuDhabi.poleLeft = False
AbuDhabi.lastYear = prevYear
AbuDhabi.lapRecordTime = "1:40.279"
AbuDhabi.lapRecordFlag = "#de"
AbuDhabi.lapRecordHolder = "Sebastian Vettel"
AbuDhabi.lapRecordTeam = "Red Bull Racing"
AbuDhabi.lapRecordYear = 2009
AbuDhabi.prevYearPoleFlag = "#fi"
AbuDhabi.prevYearPoleHolder = "Valtteri Bottas"
AbuDhabi.prevYearPoleTeam = "Mercedes"
AbuDhabi.prevYearPoleTime = "1:36.231"
AbuDhabi.prevYearFastestFlag = "#fi"
AbuDhabi.prevYearFastestHolder = "Valtteri Bottas"
AbuDhabi.prevYearFastestTeam = "Mercedes"
AbuDhabi.prevYearFastestTime = "1:40.650"
AbuDhabi.prevYearWinnerFlag = "#fi"
AbuDhabi.prevYearWinner = "Valtteri Bottas"
AbuDhabi.prevYearWinnerTeam = "Mercedes"
AbuDhabi.prevYearSecondFlag = "#gb"
AbuDhabi.prevYearSecond = "Lewis Hamilton"
AbuDhabi.prevYearSecondTeam = "Mercedes"
AbuDhabi.prevYearSecondDelta = "+3.899"
AbuDhabi.prevYearThirdFlag = "#de"
AbuDhabi.prevYearThird = "Sebatian Vettel"
AbuDhabi.prevYearThirdTeam = "Ferrari"
AbuDhabi.prevYearThirdDelta = "+19.333"
AbuDhabi.linkF1 = "https://www.formula1.com/en/championship/races/2018/Abu_Dhabi"
AbuDhabi.linkWikiCircuit = "https://en.wikipedia.org/wiki/Yas_Marina_Circuit"
AbuDhabi.linkWikiRace = "https://en.wikipedia.org/wiki/Abu_Dhabi_Grand_Prix"

#Add properties to the Malaysia weekend
Malaysia = Weekend("Malaysia")
Malaysia.fullTitle = "2018 FORMULA 1 PETRONAS MALAYSIA GRAND PRIX"
Malaysia.round = 15
Malaysia.racenr = 973
Malaysia.hubTime = datetime.datetime(currYear, 9, 28, 2, 00)
Malaysia.fp1Time = datetime.datetime(currYear, 9, 29, 3, 00)
Malaysia.fp2Time = datetime.datetime(currYear, 9, 29, 7, 00)
Malaysia.fp3Time = datetime.datetime(currYear, 9, 30, 6, 00)
Malaysia.qualiTime = datetime.datetime(currYear, 9, 30, 9, 00)
Malaysia.raceTime = datetime.datetime(currYear, 10, 1, 7, 00)
Malaysia.dadTime = datetime.datetime(currYear, 10, 2, 7, 00)
Malaysia.namean = "Malaysian"
Malaysia.flag = "#my"
Malaysia.circuit = "Sepang International Circuit"
Malaysia.city = "Kuala Lumpur"
Malaysia.weatherID = 1771287
Malaysia.firstHeld = 1962
Malaysia.length = 5.543
Malaysia.laps = 56
Malaysia.distance = 310.408
Malaysia.poleLeft = False
Malaysia.lastYear = prevYear
Malaysia.lapRecordTime = "1:34.080"
Malaysia.lapRecordFlag = "#de"
Malaysia.lapRecordHolder = "Sebastian Vettel"
Malaysia.lapRecordTeam = "Ferrari"
Malaysia.lapRecordYear = 2017
Malaysia.prevYearPoleFlag = "#gb"
Malaysia.prevYearPoleHolder = "Lewis Hamilton"
Malaysia.prevYearPoleTeam = "Mercedes"
Malaysia.prevYearPoleTime = "1:30.076"
Malaysia.prevYearFastestFlag = "#de"
Malaysia.prevYearFastestHolder = "Sebastian Vettel"
Malaysia.prevYearFastestTeam = "Ferrari"
Malaysia.prevYearFastestTime = "1:34.080"
Malaysia.prevYearWinnerFlag = "#nl"
Malaysia.prevYearWinner = "Max Verstappen"
Malaysia.prevYearWinnerTeam = "Red Bull-TAG Heuer"
Malaysia.prevYearSecondFlag = "#gb"
Malaysia.prevYearSecond = "Lewis Hamilton"
Malaysia.prevYearSecondTeam = "Mercedes"
Malaysia.prevYearSecondDelta = "+12.770"
Malaysia.prevYearThirdFlag = "#au"
Malaysia.prevYearThird = "Daniel Ricciardo"
Malaysia.prevYearThirdTeam = "Red Bull-TAG Heuer"
Malaysia.prevYearThirdDelta = "+22.519"
Malaysia.linkF1 = "https://www.formula1.com/en/championship/races/2017/Malaysia"
Malaysia.linkWikiCircuit = "https://en.wikipedia.org/wiki/Sepang_International_Circuit"
Malaysia.linkWikiRace = "https://en.wikipedia.org/wiki/Malaysian_Grand_Prix"

#Add all weekends together
allWeekends = [Australia, Bahrain, China, Azerbaijan, Spain, Monaco, Canada, France, Austria, Britain, Germany, Hungary, Belgium, Italy, Singapore, Russia, Japan, US, Mexico, Brazil, AbuDhabi]
